'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8669
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class frmCSVCompare_VN
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("_FDS.frmCSVCompare-VN", GetType(frmCSVCompare_VN).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Duyệt.
        '''</summary>
        Friend Shared ReadOnly Property APPROVE() As String
            Get
                Return ResourceManager.GetString("APPROVE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ngày backup không hợp lệ.
        '''</summary>
        Friend Shared ReadOnly Property backupNotAllow() As String
            Get
                Return ResourceManager.GetString("backupNotAllow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Đối chiếu.
        '''</summary>
        Friend Shared ReadOnly Property btnCompare() As String
            Get
                Return ResourceManager.GetString("btnCompare", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Thực hiện.
        '''</summary>
        Friend Shared ReadOnly Property btnExecute() As String
            Get
                Return ResourceManager.GetString("btnExecute", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kết xuất.
        '''</summary>
        Friend Shared ReadOnly Property btnExport() As String
            Get
                Return ResourceManager.GetString("btnExport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Xem kết quả.
        '''</summary>
        Friend Shared ReadOnly Property btnViewCmp() As String
            Get
                Return ResourceManager.GetString("btnViewCmp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Xem.
        '''</summary>
        Friend Shared ReadOnly Property btnViewFile1() As String
            Get
                Return ResourceManager.GetString("btnViewFile1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Xem.
        '''</summary>
        Friend Shared ReadOnly Property btnViewFile2() As String
            Get
                Return ResourceManager.GetString("btnViewFile2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Import.
        '''</summary>
        Friend Shared ReadOnly Property btnViewFile2Import() As String
            Get
                Return ResourceManager.GetString("btnViewFile2Import", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ghi kết quả.
        '''</summary>
        Friend Shared ReadOnly Property btnWrite() As String
            Get
                Return ResourceManager.GetString("btnWrite", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tổng số: {0} dòng, khớp: {1} dòng, lệch: {2} dòng, VSD không có: {3} dòng, Hệ thống không có: {4} dòng.
        '''</summary>
        Friend Shared ReadOnly Property cmpSummary() As String
            Get
                Return ResourceManager.GetString("cmpSummary", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Đối chiếu với VSD.
        '''</summary>
        Friend Shared ReadOnly Property CSVCompare() As String
            Get
                Return ResourceManager.GetString("CSVCompare", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File csv không có dữ liệu.
        '''</summary>
        Friend Shared ReadOnly Property csvError() As String
            Get
                Return ResourceManager.GetString("csvError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lệch ?.
        '''</summary>
        Friend Shared ReadOnly Property DEVIATION() As String
            Get
                Return ResourceManager.GetString("DEVIATION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tài khoản ký quỹ.
        '''</summary>
        Friend Shared ReadOnly Property DMACCTNO() As String
            Get
                Return ResourceManager.GetString("DMACCTNO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Không có dữ liệu.
        '''</summary>
        Friend Shared ReadOnly Property err_NO_history() As String
            Get
                Return ResourceManager.GetString("err_NO_history", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Không tìm thấy file hợp lệ! Tiếp tục lấy file lỗi điện?.
        '''</summary>
        Friend Shared ReadOnly Property errNoCorrectFile() As String
            Get
                Return ResourceManager.GetString("errNoCorrectFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Không tìm thấy file.
        '''</summary>
        Friend Shared ReadOnly Property errNoFile() As String
            Get
                Return ResourceManager.GetString("errNoFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kết xuất.
        '''</summary>
        Friend Shared ReadOnly Property EXPORT() As String
            Get
                Return ResourceManager.GetString("EXPORT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kết xuất thành công.
        '''</summary>
        Friend Shared ReadOnly Property ExportSuccessful() As String
            Get
                Return ResourceManager.GetString("ExportSuccessful", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File không hợp lệ.
        '''</summary>
        Friend Shared ReadOnly Property fileError() As String
            Get
                Return ResourceManager.GetString("fileError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Không thể thực hiện! Có dòng dữ liệu lỗi.
        '''</summary>
        Friend Shared ReadOnly Property HasErrRows() As String
            Get
                Return ResourceManager.GetString("HasErrRows", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Import.
        '''</summary>
        Friend Shared ReadOnly Property Import() As String
            Get
                Return ResourceManager.GetString("Import", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lệch.
        '''</summary>
        Friend Shared ReadOnly Property isDeviation() As String
            Get
                Return ResourceManager.GetString("isDeviation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ghi dữ liệu .
        '''</summary>
        Friend Shared ReadOnly Property issave() As String
            Get
                Return ResourceManager.GetString("issave", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loại đối chiếu.
        '''</summary>
        Friend Shared ReadOnly Property lblCompareType() As String
            Get
                Return ResourceManager.GetString("lblCompareType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ngày.
        '''</summary>
        Friend Shared ReadOnly Property lblDate() As String
            Get
                Return ResourceManager.GetString("lblDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tên file csv.
        '''</summary>
        Friend Shared ReadOnly Property lblFileName() As String
            Get
                Return ResourceManager.GetString("lblFileName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Không có kết quả đối chiếu.
        '''</summary>
        Friend Shared ReadOnly Property noCompareData() As String
            Get
                Return ResourceManager.GetString("noCompareData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Không có dữ liệu.
        '''</summary>
        Friend Shared ReadOnly Property nodata() As String
            Get
                Return ResourceManager.GetString("nodata", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Khớp.
        '''</summary>
        Friend Shared ReadOnly Property notDeviation() As String
            Get
                Return ResourceManager.GetString("notDeviation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Không có dữ liệu để kết xuất.
        '''</summary>
        Friend Shared ReadOnly Property nothingToExport() As String
            Get
                Return ResourceManager.GetString("nothingToExport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Duyệt dữ liệu.
        '''</summary>
        Friend Shared ReadOnly Property QUERY() As String
            Get
                Return ResourceManager.GetString("QUERY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Truy vấn kết quả.
        '''</summary>
        Friend Shared ReadOnly Property rdView() As String
            Get
                Return ResourceManager.GetString("rdView", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ghi hoàn tất.
        '''</summary>
        Friend Shared ReadOnly Property saveComplete() As String
            Get
                Return ResourceManager.GetString("saveComplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mã chứng khoán.
        '''</summary>
        Friend Shared ReadOnly Property SYMBOL() As String
            Get
                Return ResourceManager.GetString("SYMBOL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hệ thống.
        '''</summary>
        Friend Shared ReadOnly Property SYSTEM() As String
            Get
                Return ResourceManager.GetString("SYSTEM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hệ thống không có.
        '''</summary>
        Friend Shared ReadOnly Property SYSTEMNULL() As String
            Get
                Return ResourceManager.GetString("SYSTEMNULL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tổng số: {0} dòng.
        '''</summary>
        Friend Shared ReadOnly Property viewSummary() As String
            Get
                Return ResourceManager.GetString("viewSummary", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to VSD.
        '''</summary>
        Friend Shared ReadOnly Property VSD() As String
            Get
                Return ResourceManager.GetString("VSD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to VSD không có.
        '''</summary>
        Friend Shared ReadOnly Property VSDNULL() As String
            Get
                Return ResourceManager.GetString("VSDNULL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ghi dữ liệu.
        '''</summary>
        Friend Shared ReadOnly Property WRITE() As String
            Get
                Return ResourceManager.GetString("WRITE", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
