'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class frmFuncAssign_EN
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager(gc_RootNamespace & "." & "frmFuncAssign-EN", GetType(frmFuncAssign_EN).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Function assignment.
    '''</summary>
    Friend Shared ReadOnly Property frmFuncAssign() As String
        Get
            Return ResourceManager.GetString("frmFuncAssign", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Access right.
    '''</summary>
    Friend Shared ReadOnly Property frmFuncAssign_grbAccessRight() As String
        Get
            Return ResourceManager.GetString("frmFuncAssign.grbAccessRight", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Access.
    '''</summary>
    Friend Shared ReadOnly Property frmFuncAssign_lblACCESS() As String
        Get
            Return ResourceManager.GetString("frmFuncAssign.lblACCESS", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Addnew.
    '''</summary>
    Friend Shared ReadOnly Property frmFuncAssign_lblADD() As String
        Get
            Return ResourceManager.GetString("frmFuncAssign.lblADD", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Approve.
    '''</summary>
    Friend Shared ReadOnly Property frmFuncAssign_lblAPPROVE() As String
        Get
            Return ResourceManager.GetString("frmFuncAssign.lblAPPROVE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Function assignment for user: .
    '''</summary>
    Friend Shared ReadOnly Property frmFuncAssign_lblCaption0() As String
        Get
            Return ResourceManager.GetString("frmFuncAssign.lblCaption0", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Function assignment for group: .
    '''</summary>
    Friend Shared ReadOnly Property frmFuncAssign_lblCaption1() As String
        Get
            Return ResourceManager.GetString("frmFuncAssign.lblCaption1", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Delete.
    '''</summary>
    Friend Shared ReadOnly Property frmFuncAssign_lblDELETE() As String
        Get
            Return ResourceManager.GetString("frmFuncAssign.lblDELETE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Edit.
    '''</summary>
    Friend Shared ReadOnly Property frmFuncAssign_lblEDIT() As String
        Get
            Return ResourceManager.GetString("frmFuncAssign.lblEDIT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Inquiry.
    '''</summary>
    Friend Shared ReadOnly Property frmFuncAssign_lblINQUIRY() As String
        Get
            Return ResourceManager.GetString("frmFuncAssign.lblINQUIRY", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to User.
    '''</summary>
    Friend Shared ReadOnly Property frmFuncAssign_lblUSER() As String
        Get
            Return ResourceManager.GetString("frmFuncAssign.lblUSER", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Assign fail!.
    '''</summary>
    Friend Shared ReadOnly Property frmFuncAssign_SavingFailed() As String
        Get
            Return ResourceManager.GetString("frmFuncAssign.SavingFailed", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Function assignment successful!.
    '''</summary>
    Friend Shared ReadOnly Property frmFuncAssign_SavingSuccess() As String
        Get
            Return ResourceManager.GetString("frmFuncAssign.SavingSuccess", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Cancel.
    '''</summary>
    Friend Shared ReadOnly Property frmFuncAssign_tbnCancel() As String
        Get
            Return ResourceManager.GetString("frmFuncAssign.tbnCancel", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Save.
    '''</summary>
    Friend Shared ReadOnly Property frmFuncAssign_tbnSave() As String
        Get
            Return ResourceManager.GetString("frmFuncAssign.tbnSave", resourceCulture)
        End Get
    End Property
End Class
