'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class frmMDIMain_VN
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager(gc_RootNamespace & "." & "frmMDIMain-VN", GetType(frmMDIMain_VN).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Hoàn thành công việc!.
    '''</summary>
    Friend Shared ReadOnly Property ACTION_DONE() As String
        Get
            Return ResourceManager.GetString("ACTION_DONE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Yêu cầu đã được thực hiện.
    '''</summary>
    Friend Shared ReadOnly Property CHANGE_SUCCESS() As String
        Get
            Return ResourceManager.GetString("CHANGE_SUCCESS", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Yêu cầu đã được thực hiện.
    '''</summary>
    Friend Shared ReadOnly Property CMD_ACTION_DONE() As String
        Get
            Return ResourceManager.GetString("CMD_ACTION_DONE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Không thực hiện được yêu cầu.
    '''</summary>
    Friend Shared ReadOnly Property CMD_ACTION_FAILED() As String
        Get
            Return ResourceManager.GetString("CMD_ACTION_FAILED", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Thêm mới.
    '''</summary>
    Friend Shared ReadOnly Property ExecuteFlag_AddNew() As String
        Get
            Return ResourceManager.GetString("ExecuteFlag.AddNew", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Xoá.
    '''</summary>
    Friend Shared ReadOnly Property ExecuteFlag_Delete() As String
        Get
            Return ResourceManager.GetString("ExecuteFlag.Delete", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Sửa.
    '''</summary>
    Friend Shared ReadOnly Property ExecuteFlag_Edit() As String
        Get
            Return ResourceManager.GetString("ExecuteFlag.Edit", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Xem.
    '''</summary>
    Friend Shared ReadOnly Property ExecuteFlag_View() As String
        Get
            Return ResourceManager.GetString("ExecuteFlag.View", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Bạn có muốn thoát khỏi hệ thống?.
    '''</summary>
    Friend Shared ReadOnly Property EXIT_CONFIRMATION() As String
        Get
            Return ResourceManager.GetString("EXIT_CONFIRMATION", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Kết xuất.
    '''</summary>
    Friend Shared ReadOnly Property frmMDIMain_btnExport() As String
        Get
            Return ResourceManager.GetString("frmMDIMain.btnExport", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Tìm kiếm.
    '''</summary>
    Friend Shared ReadOnly Property frmMDIMain_btnSearch() As String
        Get
            Return ResourceManager.GetString("frmMDIMain.btnSearch", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Submit.
    '''</summary>
    Friend Shared ReadOnly Property frmMDIMain_btnSUBMIT() As String
        Get
            Return ResourceManager.GetString("frmMDIMain.btnSUBMIT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Đồng ý xoá dữ liệu?.
    '''</summary>
    Friend Shared ReadOnly Property frmMDIMain_DelConfirm() As String
        Get
            Return ResourceManager.GetString("frmMDIMain.DelConfirm", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Xoá dữ liệu thành công!.
    '''</summary>
    Friend Shared ReadOnly Property frmMDIMain_DelSuccess() As String
        Get
            Return ResourceManager.GetString("frmMDIMain.DelSuccess", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Đây là footer, không thể xem, sửa, xoá dữ liệu!.
    '''</summary>
    Friend Shared ReadOnly Property frmMDIMain_Footer() As String
        Get
            Return ResourceManager.GetString("frmMDIMain.Footer", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Điều kiện:.
    '''</summary>
    Friend Shared ReadOnly Property frmMDIMain_grbCondition() As String
        Get
            Return ResourceManager.GetString("frmMDIMain.grbCondition", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Danh sách điều kiện tìm kiếm:.
    '''</summary>
    Friend Shared ReadOnly Property frmMDIMain_grbConditionList() As String
        Get
            Return ResourceManager.GetString("frmMDIMain.grbConditionList", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Điều kiện tìm kiếm:.
    '''</summary>
    Friend Shared ReadOnly Property frmMDIMain_grbSearchFilter() As String
        Get
            Return ResourceManager.GetString("frmMDIMain.grbSearchFilter", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Kết quả tìm kiếm:.
    '''</summary>
    Friend Shared ReadOnly Property frmMDIMain_grbSearchResult() As String
        Get
            Return ResourceManager.GetString("frmMDIMain.grbSearchResult", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tiêu chí:.
    '''</summary>
    Friend Shared ReadOnly Property frmMDIMain_lblField() As String
        Get
            Return ResourceManager.GetString("frmMDIMain.lblField", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Điều kiện:.
    '''</summary>
    Friend Shared ReadOnly Property frmMDIMain_lblOperator() As String
        Get
            Return ResourceManager.GetString("frmMDIMain.lblOperator", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Giá trị:.
    '''</summary>
    Friend Shared ReadOnly Property frmMDIMain_lblValue() As String
        Get
            Return ResourceManager.GetString("frmMDIMain.lblValue", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Phải chọn dòng thông tin cần xem, sửa, xoá!.
    '''</summary>
    Friend Shared ReadOnly Property frmMDIMain_NotSelected() As String
        Get
            Return ResourceManager.GetString("frmMDIMain.NotSelected", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Đang thực hiện tìm kiếm....
    '''</summary>
    Friend Shared ReadOnly Property frmMDIMain_Searching() As String
        Get
            Return ResourceManager.GetString("frmMDIMain.Searching", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Quỹ.
    '''</summary>
    Friend Shared ReadOnly Property frmMDIMain_tbnAdd() As String
        Get
            Return ResourceManager.GetString("frmMDIMain.tbnAdd", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Xoá.
    '''</summary>
    Friend Shared ReadOnly Property frmMDIMain_tbnDelete() As String
        Get
            Return ResourceManager.GetString("frmMDIMain.tbnDelete", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Duyệt.
    '''</summary>
    Friend Shared ReadOnly Property frmMDIMain_tbnEdit() As String
        Get
            Return ResourceManager.GetString("frmMDIMain.tbnEdit", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Không duyệt.
    '''</summary>
    Friend Shared ReadOnly Property frmMDIMain_tbnExit() As String
        Get
            Return ResourceManager.GetString("frmMDIMain.tbnExit", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Xem.
    '''</summary>
    Friend Shared ReadOnly Property frmMDIMain_tbnView() As String
        Get
            Return ResourceManager.GetString("frmMDIMain.tbnView", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Chức năng này chưa được cài đặt.
    '''</summary>
    Friend Shared ReadOnly Property FUNCTION_ISNOT_IMPLEMENTED() As String
        Get
            Return ResourceManager.GetString("FUNCTION_ISNOT_IMPLEMENTED", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tổng số bản ghi tìm kiếm: .
    '''</summary>
    Friend Shared ReadOnly Property GridEx_FooterRow() As String
        Get
            Return ResourceManager.GetString("GridEx.FooterRow", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Hãy kéo cột cần nhóm vào đây!.
    '''</summary>
    Friend Shared ReadOnly Property GridEx_GroupByRow() As String
        Get
            Return ResourceManager.GetString("GridEx.GroupByRow", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Bạn có muốn thoát ra và đăng nhập với user khác?.
    '''</summary>
    Friend Shared ReadOnly Property LOGOUT_CONFIRMATION() As String
        Get
            Return ResourceManager.GetString("LOGOUT_CONFIRMATION", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Ẩn/hiện chức năng nhóm.
    '''</summary>
    Friend Shared ReadOnly Property mnuHideCustomizeMenu() As String
        Get
            Return ResourceManager.GetString("mnuHideCustomizeMenu", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Ẩn/hiện chức năng hệ thống.
    '''</summary>
    Friend Shared ReadOnly Property mnuHideSystemMenu() As String
        Get
            Return ResourceManager.GetString("mnuHideSystemMenu", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Chương trình sẽ cập nhật bảng mới,nhấn OK tiếp tục..
    '''</summary>
    Friend Shared ReadOnly Property MSG_APPUPDATE() As String
        Get
            Return ResourceManager.GetString("MSG_APPUPDATE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Chương trình tự động cập nhật bản mới
    '''Phiên bản hiện tại: {0}
    '''Phiên bản mới nhất: {1}
    '''Nhấn OK tiếp tục..
    '''</summary>
    Friend Shared ReadOnly Property MSG_UPDATESTRING() As String
        Get
            Return ResourceManager.GetString("MSG_UPDATESTRING", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Bạn không có quyền thực hiện giao dịch này, liên hệ quản trị hệ thống !.
    '''</summary>
    Friend Shared ReadOnly Property NotAllowTrans() As String
        Get
            Return ResourceManager.GetString("NotAllowTrans", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Xin lỗi quý vị, hiện tại chức năng này chưa được xây dựng!.
    '''</summary>
    Friend Shared ReadOnly Property SRRFunctionNotBuild() As String
        Get
            Return ResourceManager.GetString("SRRFunctionNotBuild", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Mã giao dịch:.
    '''</summary>
    Friend Shared ReadOnly Property TRANSACTION_CODE() As String
        Get
            Return ResourceManager.GetString("TRANSACTION_CODE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Chức năng không tồn tại, không được gọi trực tiếp hoặc bạn không đủ quyền sử dụng chức năng này!.
    '''</summary>
    Friend Shared ReadOnly Property TransViaGenaralView() As String
        Get
            Return ResourceManager.GetString("TransViaGenaralView", resourceCulture)
        End Get
    End Property
End Class
