'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class frmReadFile_VN
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager(gc_RootNamespace & "." & "frmReadFile-VN", GetType(frmReadFile_VN).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mã sự kiện thực hiện quyền chưa được chọn !.
        '''</summary>
        Friend Shared ReadOnly Property ERR_CANOTSELECT() As String
            Get
                Return ResourceManager.GetString("ERR_CANOTSELECT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Không có dữ liệu được đồng bộ vào hệ thống!.
        '''</summary>
        Friend Shared ReadOnly Property ERR_CANTWRITE() As String
            Get
                Return ResourceManager.GetString("ERR_CANTWRITE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Định dạng file dữ liệu không hợp lệ. Vui lòng chuẩn hóa lại file dữ liệu trước khi đồng bộ file!.
        '''</summary>
        Friend Shared ReadOnly Property ERR_DATAFORMAT() As String
            Get
                Return ResourceManager.GetString("ERR_DATAFORMAT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Đường dẫn không hợp lệ, vui lòng chọn lại đường dẫn!.
        '''</summary>
        Friend Shared ReadOnly Property ERR_FILEPATH() As String
            Get
                Return ResourceManager.GetString("ERR_FILEPATH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File dư liệu đầu vào không hợp lệ!!.
        '''</summary>
        Friend Shared ReadOnly Property ERR_IMPUTFILEFORMAT() As String
            Get
                Return ResourceManager.GetString("ERR_IMPUTFILEFORMAT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bạn có muốn ghi dữ liệu bây giờ?.
        '''</summary>
        Friend Shared ReadOnly Property MSG_CONFIRM() As String
            Get
                Return ResourceManager.GetString("MSG_CONFIRM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vui lòng chọn đường dẫn đến file.xsl cần đọc!.
        '''</summary>
        Friend Shared ReadOnly Property MSG_FILEPATH() As String
            Get
                Return ResourceManager.GetString("MSG_FILEPATH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ghi dữ liệu thành công.
        '''</summary>
        Friend Shared ReadOnly Property MSG_SUCCESS() As String
            Get
                Return ResourceManager.GetString("MSG_SUCCESS", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
