'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class frmRightAssignment_VN
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager(gc_RootNamespace & "." & "frmRightAssignment-VN", GetType(frmRightAssignment_VN).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Hạn mức thanh toán phải là số dương!.
    '''</summary>
    Friend Shared ReadOnly Property CashierMsg() As String
        Get
            Return ResourceManager.GetString("CashierMsg", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Hạn mức duyệt rủi ro phải là số dương!.
    '''</summary>
    Friend Shared ReadOnly Property CheckerMsg() As String
        Get
            Return ResourceManager.GetString("CheckerMsg", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Truy nhập.
    '''</summary>
    Friend Shared ReadOnly Property ckbGNRACC() As String
        Get
            Return ResourceManager.GetString("ckbGNRACC", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tạo báo cáo/Xem dữ liệu.
    '''</summary>
    Friend Shared ReadOnly Property ckbRPTADD() As String
        Get
            Return ResourceManager.GetString("ckbRPTADD", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to In.
    '''</summary>
    Friend Shared ReadOnly Property ckbRPTPRINT() As String
        Get
            Return ResourceManager.GetString("ckbRPTPRINT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Xem.
    '''</summary>
    Friend Shared ReadOnly Property ckbRPTVIEW() As String
        Get
            Return ResourceManager.GetString("ckbRPTVIEW", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Phân quyền sử dụng hệ thống.
    '''</summary>
    Friend Shared ReadOnly Property frmRightAssignment() As String
        Get
            Return ResourceManager.GetString("frmRightAssignment", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Phân quyền chức năng.
    '''</summary>
    Friend Shared ReadOnly Property grbAccessRight() As String
        Get
            Return ResourceManager.GetString("grbAccessRight", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Phân quyền tra cứu tổng hợp.
    '''</summary>
    Friend Shared ReadOnly Property grbGnrAccessRight() As String
        Get
            Return ResourceManager.GetString("grbGnrAccessRight", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Phân quyền báo cáo.
    '''</summary>
    Friend Shared ReadOnly Property grbRptAccessRight() As String
        Get
            Return ResourceManager.GetString("grbRptAccessRight", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Phân quyền giao dịch.
    '''</summary>
    Friend Shared ReadOnly Property grbTransAccessRight() As String
        Get
            Return ResourceManager.GetString("grbTransAccessRight", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Truy nhập.
    '''</summary>
    Friend Shared ReadOnly Property lblACCESS() As String
        Get
            Return ResourceManager.GetString("lblACCESS", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Thêm mới.
    '''</summary>
    Friend Shared ReadOnly Property lblADD() As String
        Get
            Return ResourceManager.GetString("lblADD", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Duyệt.
    '''</summary>
    Friend Shared ReadOnly Property lblAPPROVE() As String
        Get
            Return ResourceManager.GetString("lblAPPROVE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Phân quyền cho người sử dụng: .
    '''</summary>
    Friend Shared ReadOnly Property lblCaption0() As String
        Get
            Return ResourceManager.GetString("lblCaption0", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Phân quyền cho nhóm NSD: .
    '''</summary>
    Friend Shared ReadOnly Property lblCaption1() As String
        Get
            Return ResourceManager.GetString("lblCaption1", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Hạn mức thanh toán:.
    '''</summary>
    Friend Shared ReadOnly Property lblCASHIERLIMIT() As String
        Get
            Return ResourceManager.GetString("lblCASHIERLIMIT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Hạn mức duyệt rủi ro:.
    '''</summary>
    Friend Shared ReadOnly Property lblCHECKERLIMIT() As String
        Get
            Return ResourceManager.GetString("lblCHECKERLIMIT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Mã tiền tệ:.
    '''</summary>
    Friend Shared ReadOnly Property lblCURRCOD() As String
        Get
            Return ResourceManager.GetString("lblCURRCOD", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Xoá.
    '''</summary>
    Friend Shared ReadOnly Property lblDELETE() As String
        Get
            Return ResourceManager.GetString("lblDELETE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Sửa.
    '''</summary>
    Friend Shared ReadOnly Property lblEDIT() As String
        Get
            Return ResourceManager.GetString("lblEDIT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Hạn mức thanh toán:.
    '''</summary>
    Friend Shared ReadOnly Property lblGNRCASHIERLM() As String
        Get
            Return ResourceManager.GetString("lblGNRCASHIERLM", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Hạn mức duyệt rủi ro:.
    '''</summary>
    Friend Shared ReadOnly Property lblGNRCHECKERLM() As String
        Get
            Return ResourceManager.GetString("lblGNRCHECKERLM", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Mã tiền tệ:.
    '''</summary>
    Friend Shared ReadOnly Property lblGNRCURR() As String
        Get
            Return ResourceManager.GetString("lblGNRCURR", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Hạn mức duyệt:.
    '''</summary>
    Friend Shared ReadOnly Property lblGNROFFICERLM() As String
        Get
            Return ResourceManager.GetString("lblGNROFFICERLM", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Hạn mức nhập GD:.
    '''</summary>
    Friend Shared ReadOnly Property lblGNRTELLERLM() As String
        Get
            Return ResourceManager.GetString("lblGNRTELLERLM", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Xem.
    '''</summary>
    Friend Shared ReadOnly Property lblINQUIRY() As String
        Get
            Return ResourceManager.GetString("lblINQUIRY", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Hạn mức duyệt:.
    '''</summary>
    Friend Shared ReadOnly Property lblOFFICERLIMIT() As String
        Get
            Return ResourceManager.GetString("lblOFFICERLIMIT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Phạm vi:.
    '''</summary>
    Friend Shared ReadOnly Property lblRPTAREA() As String
        Get
            Return ResourceManager.GetString("lblRPTAREA", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Hạn mức nhập GD:.
    '''</summary>
    Friend Shared ReadOnly Property lblTELLERLIMIT() As String
        Get
            Return ResourceManager.GetString("lblTELLERLIMIT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Người sử dụng:.
    '''</summary>
    Friend Shared ReadOnly Property lblUSER() As String
        Get
            Return ResourceManager.GetString("lblUSER", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Hạn mức duyệt phải là số dương!.
    '''</summary>
    Friend Shared ReadOnly Property OfficerMsg() As String
        Get
            Return ResourceManager.GetString("OfficerMsg", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Phân quyền không thành công!.
    '''</summary>
    Friend Shared ReadOnly Property SavingFailed() As String
        Get
            Return ResourceManager.GetString("SavingFailed", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Phân quyền thành công!.
    '''</summary>
    Friend Shared ReadOnly Property SavingSuccess() As String
        Get
            Return ResourceManager.GetString("SavingSuccess", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Thoát.
    '''</summary>
    Friend Shared ReadOnly Property tbnCancel() As String
        Get
            Return ResourceManager.GetString("tbnCancel", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Chấp nhận.
    '''</summary>
    Friend Shared ReadOnly Property tbnSave() As String
        Get
            Return ResourceManager.GetString("tbnSave", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Hạn mức nhập giao dịch phải là số dương!.
    '''</summary>
    Friend Shared ReadOnly Property TellerMsg() As String
        Get
            Return ResourceManager.GetString("TellerMsg", resourceCulture)
        End Get
    End Property
End Class
