'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class frmTransactEx_VN
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager(gc_RootNamespace & "." & "frmTransactEx-VN", GetType(frmTransactEx_VN).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tên loại hình.
    '''</summary>
    Friend Shared ReadOnly Property ACCOUNT_ACTYPE() As String
        Get
            Return ResourceManager.GetString("ACCOUNT_ACTYPE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tiểu khoản.
    '''</summary>
    Friend Shared ReadOnly Property ACCOUNT_AFACCTNO() As String
        Get
            Return ResourceManager.GetString("ACCOUNT_AFACCTNO", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Số tiền GD.
    '''</summary>
    Friend Shared ReadOnly Property ACCOUNT_AFAMT() As String
        Get
            Return ResourceManager.GetString("ACCOUNT_AFAMT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Số tiền GD tối đa.
    '''</summary>
    Friend Shared ReadOnly Property ACCOUNT_AVAILAFAMT() As String
        Get
            Return ResourceManager.GetString("ACCOUNT_AVAILAFAMT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Phí GD.
    '''</summary>
    Friend Shared ReadOnly Property ACCOUNT_FEEAMT() As String
        Get
            Return ResourceManager.GetString("ACCOUNT_FEEAMT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Trạng thái.
    '''</summary>
    Friend Shared ReadOnly Property ACCOUNT_STATUS_DESC() As String
        Get
            Return ResourceManager.GetString("ACCOUNT_STATUS_DESC", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Thuế.
    '''</summary>
    Friend Shared ReadOnly Property ACCOUNT_VATAMT() As String
        Get
            Return ResourceManager.GetString("ACCOUNT_VATAMT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Chấp nhận.
    '''</summary>
    Friend Shared ReadOnly Property btnApply() As String
        Get
            Return ResourceManager.GetString("btnApply", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Thoát.
    '''</summary>
    Friend Shared ReadOnly Property btnCancel() As String
        Get
            Return ResourceManager.GetString("btnCancel", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to In chứng từ.
    '''</summary>
    Friend Shared ReadOnly Property btnPrint() As String
        Get
            Return ResourceManager.GetString("btnPrint", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to In chi tiết.
    '''</summary>
    Friend Shared ReadOnly Property btnSubPrint() As String
        Get
            Return ResourceManager.GetString("btnSubPrint", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Không tìm thấy mẫu file báo cáo!.
    '''</summary>
    Friend Shared ReadOnly Property CANNOT_FOUND_RPT_FILE() As String
        Get
            Return ResourceManager.GetString("CANNOT_FOUND_RPT_FILE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Đồng ý thực hiện giao dịch &lt;&lt;TXDESC&gt;&gt; ?.
    '''</summary>
    Friend Shared ReadOnly Property ConfirmApply() As String
        Get
            Return ResourceManager.GetString("ConfirmApply", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Giao dịch liên tiểu khoản.
    '''</summary>
    Friend Shared ReadOnly Property frmTransactEx() As String
        Get
            Return ResourceManager.GetString("frmTransactEx", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Thông tin khách hàng.
    '''</summary>
    Friend Shared ReadOnly Property grbCFInfo() As String
        Get
            Return ResourceManager.GetString("grbCFInfo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Thông tin giao dịch chuyển tiền ra ngân hàng.
    '''</summary>
    Friend Shared ReadOnly Property grbExternalTransfer() As String
        Get
            Return ResourceManager.GetString("grbExternalTransfer", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Thông tin giao dịch chuyển khoản nội bộ.
    '''</summary>
    Friend Shared ReadOnly Property grbInternalTransfer() As String
        Get
            Return ResourceManager.GetString("grbInternalTransfer", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Chuyển khoản nội bộ (liên tiểu khoản).
    '''</summary>
    Friend Shared ReadOnly Property INTERNALTRANSFER_DESC() As String
        Get
            Return ResourceManager.GetString("INTERNALTRANSFER_DESC", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Trường Số TK thụ hưởng bắt buộc nhập!.
    '''</summary>
    Friend Shared ReadOnly Property INVALID_BENEFACCT() As String
        Get
            Return ResourceManager.GetString("INVALID_BENEFACCT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Trường Tên NH thụ hưởng bắt buộc nhập!.
    '''</summary>
    Friend Shared ReadOnly Property INVALID_BENEFBANK() As String
        Get
            Return ResourceManager.GetString("INVALID_BENEFBANK", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Trường Tên KH thụ hưởng bắt buộc nhập!.
    '''</summary>
    Friend Shared ReadOnly Property INVALID_BENEFCUSTNAME() As String
        Get
            Return ResourceManager.GetString("INVALID_BENEFCUSTNAME", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Trường biểu phí bắt buộc nhập!.
    '''</summary>
    Friend Shared ReadOnly Property INVALID_FEECD() As String
        Get
            Return ResourceManager.GetString("INVALID_FEECD", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Giá trị số không hợp lệ!.
    '''</summary>
    Friend Shared ReadOnly Property INVALID_NUMERIC() As String
        Get
            Return ResourceManager.GetString("INVALID_NUMERIC", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Số tiền nhập vào không hợp lệ!.
    '''</summary>
    Friend Shared ReadOnly Property INVALIDAMOUNT() As String
        Get
            Return ResourceManager.GetString("INVALIDAMOUNT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Thông tin giao dịch bắt buộc nhập!.
    '''</summary>
    Friend Shared ReadOnly Property INVALIDCUSTINFO() As String
        Get
            Return ResourceManager.GetString("INVALIDCUSTINFO", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Số tài khoản lưu ký không hợp lệ!.
    '''</summary>
    Friend Shared ReadOnly Property INVALIDCUSTODYCD() As String
        Get
            Return ResourceManager.GetString("INVALIDCUSTODYCD", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Địa chỉ:.
    '''</summary>
    Friend Shared ReadOnly Property lblADDRESS() As String
        Get
            Return ResourceManager.GetString("lblADDRESS", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Địa chỉ:.
    '''</summary>
    Friend Shared ReadOnly Property lblADDRESS2() As String
        Get
            Return ResourceManager.GetString("lblADDRESS2", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Số TK 2:.
    '''</summary>
    Friend Shared ReadOnly Property lblAFACCTNO2() As String
        Get
            Return ResourceManager.GetString("lblAFACCTNO2", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Số tiền GD:.
    '''</summary>
    Friend Shared ReadOnly Property lblAMT() As String
        Get
            Return ResourceManager.GetString("lblAMT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Số tiền GD tối đa:.
    '''</summary>
    Friend Shared ReadOnly Property lblAVAILAMT() As String
        Get
            Return ResourceManager.GetString("lblAVAILAMT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Số TK thụ hưởng:.
    '''</summary>
    Friend Shared ReadOnly Property lblBENEFACCT() As String
        Get
            Return ResourceManager.GetString("lblBENEFACCT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tên NH thụ hưởng:.
    '''</summary>
    Friend Shared ReadOnly Property lblBENEFBANK() As String
        Get
            Return ResourceManager.GetString("lblBENEFBANK", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tên KH thụ hưởng:.
    '''</summary>
    Friend Shared ReadOnly Property lblBENEFCUSTNAME() As String
        Get
            Return ResourceManager.GetString("lblBENEFCUSTNAME", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Số TK lưu ký:.
    '''</summary>
    Friend Shared ReadOnly Property lblCUSTODYCD() As String
        Get
            Return ResourceManager.GetString("lblCUSTODYCD", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Số TK lưu ký 2:.
    '''</summary>
    Friend Shared ReadOnly Property lblCUSTODYCD2() As String
        Get
            Return ResourceManager.GetString("lblCUSTODYCD2", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Diễn giải:.
    '''</summary>
    Friend Shared ReadOnly Property lblDESC() As String
        Get
            Return ResourceManager.GetString("lblDESC", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Thực chuyển:.
    '''</summary>
    Friend Shared ReadOnly Property lblETAMT() As String
        Get
            Return ResourceManager.GetString("lblETAMT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Số phí:.
    '''</summary>
    Friend Shared ReadOnly Property lblFEEAMT() As String
        Get
            Return ResourceManager.GetString("lblFEEAMT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Biểu phí:.
    '''</summary>
    Friend Shared ReadOnly Property lblFEECD() As String
        Get
            Return ResourceManager.GetString("lblFEECD", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Số CMT:.
    '''</summary>
    Friend Shared ReadOnly Property lblIDCODE() As String
        Get
            Return ResourceManager.GetString("lblIDCODE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Số CMT:.
    '''</summary>
    Friend Shared ReadOnly Property lblIDCODE2() As String
        Get
            Return ResourceManager.GetString("lblIDCODE2", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Ngày ĐK:.
    '''</summary>
    Friend Shared ReadOnly Property lblIDDATE() As String
        Get
            Return ResourceManager.GetString("lblIDDATE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Ngày ĐK:.
    '''</summary>
    Friend Shared ReadOnly Property lblIDDATE2() As String
        Get
            Return ResourceManager.GetString("lblIDDATE2", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Nơi cấp:.
    '''</summary>
    Friend Shared ReadOnly Property lblIDPLACE() As String
        Get
            Return ResourceManager.GetString("lblIDPLACE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Nơi cấp:.
    '''</summary>
    Friend Shared ReadOnly Property lblIDPLACE2() As String
        Get
            Return ResourceManager.GetString("lblIDPLACE2", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Kiểu phí:.
    '''</summary>
    Friend Shared ReadOnly Property lblIORO() As String
        Get
            Return ResourceManager.GetString("lblIORO", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Mã tham chiếu:.
    '''</summary>
    Friend Shared ReadOnly Property lblREFID() As String
        Get
            Return ResourceManager.GetString("lblREFID", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Số tiền còn lại:.
    '''</summary>
    Friend Shared ReadOnly Property lblREMAINAMT() As String
        Get
            Return ResourceManager.GetString("lblREMAINAMT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Người yêu cầu:.
    '''</summary>
    Friend Shared ReadOnly Property lblRQSNAME() As String
        Get
            Return ResourceManager.GetString("lblRQSNAME", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Số thuế:.
    '''</summary>
    Friend Shared ReadOnly Property lblVATAMT() As String
        Get
            Return ResourceManager.GetString("lblVATAMT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Thực hiện giao dịch thành công!.
    '''</summary>
    Friend Shared ReadOnly Property TransactionSuccessful() As String
        Get
            Return ResourceManager.GetString("TransactionSuccessful", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Chuyển khoản ra ngân hàng (liên tiểu khoản).
    '''</summary>
    Friend Shared ReadOnly Property TRANSFER2BANK_DESC() As String
        Get
            Return ResourceManager.GetString("TRANSFER2BANK_DESC", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Số CT.
    '''</summary>
    Friend Shared ReadOnly Property TXNUM() As String
        Get
            Return ResourceManager.GetString("TXNUM", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Rút tiền (liên tiểu khoàn).
    '''</summary>
    Friend Shared ReadOnly Property WITHDRAWN_DESC() As String
        Get
            Return ResourceManager.GetString("WITHDRAWN_DESC", resourceCulture)
        End Get
    End Property
End Class
