'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class Localize_EN
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager(gc_RootNamespace & "." & "Localize-EN", GetType(Localize_EN).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Are you sure to active branch?.
    '''</summary>
    Friend Shared ReadOnly Property ACTIVE_BDS_CONFIRMATION() As String
        Get
            Return ResourceManager.GetString("ACTIVE_BDS_CONFIRMATION", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Are you sure to active host?.
    '''</summary>
    Friend Shared ReadOnly Property ACTIVE_HOST_CONFIRMATION() As String
        Get
            Return ResourceManager.GetString("ACTIVE_HOST_CONFIRMATION", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Begin with.
    '''</summary>
    Friend Shared ReadOnly Property BEGIN_WITH() As String
        Get
            Return ResourceManager.GetString("BEGIN_WITH", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Are you sure to change system language from English to Tiếng Việt? You must restart your application!.
    '''</summary>
    Friend Shared ReadOnly Property CHANGE_LANGUAGE_CONFIRMATION() As String
        Get
            Return ResourceManager.GetString("CHANGE_LANGUAGE_CONFIRMATION", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Are you sure to deactive branch?.
    '''</summary>
    Friend Shared ReadOnly Property DEACTIVE_BDS_CONFIRMATION() As String
        Get
            Return ResourceManager.GetString("DEACTIVE_BDS_CONFIRMATION", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Are you sure to deactive host?.
    '''</summary>
    Friend Shared ReadOnly Property DEACTIVE_HOST_CONFIRMATION() As String
        Get
            Return ResourceManager.GetString("DEACTIVE_HOST_CONFIRMATION", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to --All--.
    '''</summary>
    Friend Shared ReadOnly Property DURATION_ALL() As String
        Get
            Return ResourceManager.GetString("DURATION_ALL", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to From date ... To date ....
    '''</summary>
    Friend Shared ReadOnly Property DURATION_FROM_DATE_TO_DATE() As String
        Get
            Return ResourceManager.GetString("DURATION_FROM_DATE_TO_DATE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to 2 week ago.
    '''</summary>
    Friend Shared ReadOnly Property DURATION_LAST_2_WEEK() As String
        Get
            Return ResourceManager.GetString("DURATION_LAST_2_WEEK", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to 3 month ago.
    '''</summary>
    Friend Shared ReadOnly Property DURATION_LAST_3_MONTH() As String
        Get
            Return ResourceManager.GetString("DURATION_LAST_3_MONTH", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to 30 day ago.
    '''</summary>
    Friend Shared ReadOnly Property DURATION_LAST_30_DAYS() As String
        Get
            Return ResourceManager.GetString("DURATION_LAST_30_DAYS", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to 4 week ago.
    '''</summary>
    Friend Shared ReadOnly Property DURATION_LAST_4_WEEK() As String
        Get
            Return ResourceManager.GetString("DURATION_LAST_4_WEEK", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to 6 month ago.
    '''</summary>
    Friend Shared ReadOnly Property DURATION_LAST_6_MONTH() As String
        Get
            Return ResourceManager.GetString("DURATION_LAST_6_MONTH", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to In month.
    '''</summary>
    Friend Shared ReadOnly Property DURATION_MONTH() As String
        Get
            Return ResourceManager.GetString("DURATION_MONTH", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to To date ....
    '''</summary>
    Friend Shared ReadOnly Property DURATION_TO_DATE() As String
        Get
            Return ResourceManager.GetString("DURATION_TO_DATE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to In day.
    '''</summary>
    Friend Shared ReadOnly Property DURATION_TODATE() As String
        Get
            Return ResourceManager.GetString("DURATION_TODATE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to In week.
    '''</summary>
    Friend Shared ReadOnly Property DURATION_WEEK() As String
        Get
            Return ResourceManager.GetString("DURATION_WEEK", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to In year.
    '''</summary>
    Friend Shared ReadOnly Property DURATION_YEAR() As String
        Get
            Return ResourceManager.GetString("DURATION_YEAR", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to End with.
    '''</summary>
    Friend Shared ReadOnly Property END_WITH() As String
        Get
            Return ResourceManager.GetString("END_WITH", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Are you sure to quit program?.
    '''</summary>
    Friend Shared ReadOnly Property EXIT_CONFIRMATION() As String
        Get
            Return ResourceManager.GetString("EXIT_CONFIRMATION", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Help.
    '''</summary>
    Friend Shared ReadOnly Property frmMDIMain_mnuHelp() As String
        Get
            Return ResourceManager.GetString("frmMDIMain.mnuHelp", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to About....
    '''</summary>
    Friend Shared ReadOnly Property frmMDIMain_mnuHelpAbout() As String
        Get
            Return ResourceManager.GetString("frmMDIMain.mnuHelpAbout", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to User&apos;s Guide.
    '''</summary>
    Friend Shared ReadOnly Property frmMDIMain_mnuHelpUserManual() As String
        Get
            Return ResourceManager.GetString("frmMDIMain.mnuHelpUserManual", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to English.
    '''</summary>
    Friend Shared ReadOnly Property frmMDIMain_mnuLangEnglish() As String
        Get
            Return ResourceManager.GetString("frmMDIMain.mnuLangEnglish", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Language.
    '''</summary>
    Friend Shared ReadOnly Property frmMDIMain_mnuLanguage() As String
        Get
            Return ResourceManager.GetString("frmMDIMain.mnuLanguage", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Vietnamese.
    '''</summary>
    Friend Shared ReadOnly Property frmMDIMain_mnuLangVietnamese() As String
        Get
            Return ResourceManager.GetString("frmMDIMain.mnuLangVietnamese", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;System.
    '''</summary>
    Friend Shared ReadOnly Property frmMDIMain_mnuSys() As String
        Get
            Return ResourceManager.GetString("frmMDIMain.mnuSys", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Change password....
    '''</summary>
    Friend Shared ReadOnly Property frmMDIMain_mnuSysChangePassword() As String
        Get
            Return ResourceManager.GetString("frmMDIMain.mnuSysChangePassword", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Exit.
    '''</summary>
    Friend Shared ReadOnly Property frmMDIMain_mnuSysExit() As String
        Get
            Return ResourceManager.GetString("frmMDIMain.mnuSysExit", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to LogIn.
    '''</summary>
    Friend Shared ReadOnly Property frmMDIMain_mnuSysLogin() As String
        Get
            Return ResourceManager.GetString("frmMDIMain.mnuSysLogin", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to LogOut.
    '''</summary>
    Friend Shared ReadOnly Property frmMDIMain_mnuSysLogout() As String
        Get
            Return ResourceManager.GetString("frmMDIMain.mnuSysLogout", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Branch.
    '''</summary>
    Friend Shared ReadOnly Property frmMDIMain_sbrPanelBranch() As String
        Get
            Return ResourceManager.GetString("frmMDIMain.sbrPanelBranch", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to System date, time.
    '''</summary>
    Friend Shared ReadOnly Property frmMDIMain_sbrPanelDateTime() As String
        Get
            Return ResourceManager.GetString("frmMDIMain.sbrPanelDateTime", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to System status.
    '''</summary>
    Friend Shared ReadOnly Property frmMDIMain_sbrPanelStatus() As String
        Get
            Return ResourceManager.GetString("frmMDIMain.sbrPanelStatus", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Current user.
    '''</summary>
    Friend Shared ReadOnly Property frmMDIMain_sbrPanelUser() As String
        Get
            Return ResourceManager.GetString("frmMDIMain.sbrPanelUser", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Are you sure to log out program?.
    '''</summary>
    Friend Shared ReadOnly Property LOGOUT_CONFIRMATION() As String
        Get
            Return ResourceManager.GetString("LOGOUT_CONFIRMATION", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Program will auto update, press OK to continue!.
    '''</summary>
    Friend Shared ReadOnly Property MSG_APPUPDATE() As String
        Get
            Return ResourceManager.GetString("MSG_APPUPDATE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Please choose path .xsl file !.
    '''</summary>
    Friend Shared ReadOnly Property MSG_FILEPATH() As String
        Get
            Return ResourceManager.GetString("MSG_FILEPATH", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Report will auto update
    '''Current report version: {0}
    '''New report version: {1}
    '''Press ok to continue..
    '''</summary>
    Friend Shared ReadOnly Property MSG_UPDATESRPTRING() As String
        Get
            Return ResourceManager.GetString("MSG_UPDATESRPTRING", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Program will auto update
    '''Current version: {0}
    '''New version: {1}
    '''Press ok to continue..
    '''</summary>
    Friend Shared ReadOnly Property MSG_UPDATESTRING() As String
        Get
            Return ResourceManager.GetString("MSG_UPDATESTRING", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to You can not make this transaction, contact your system administrator!.
    '''</summary>
    Friend Shared ReadOnly Property NotAllowTrans() As String
        Get
            Return ResourceManager.GetString("NotAllowTrans", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Search all!.
    '''</summary>
    Friend Shared ReadOnly Property SEARCH_MSG_ALL() As String
        Get
            Return ResourceManager.GetString("SEARCH_MSG_ALL", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Search with condition !.
    '''</summary>
    Friend Shared ReadOnly Property SEARCH_MSG_CONDITION() As String
        Get
            Return ResourceManager.GetString("SEARCH_MSG_CONDITION", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Sorry you, now this function has not been built!.
    '''</summary>
    Friend Shared ReadOnly Property SRRFunctionNotBuild() As String
        Get
            Return ResourceManager.GetString("SRRFunctionNotBuild", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Loading menu. Please wait....
    '''</summary>
    Friend Shared ReadOnly Property STATUS_LOADING_MENU() As String
        Get
            Return ResourceManager.GetString("STATUS_LOADING_MENU", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Loading parameters. Please wait....
    '''</summary>
    Friend Shared ReadOnly Property STATUS_LOADING_PARAMS() As String
        Get
            Return ResourceManager.GetString("STATUS_LOADING_PARAMS", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Working.....
    '''</summary>
    Friend Shared ReadOnly Property STATUS_WORKING() As String
        Get
            Return ResourceManager.GetString("STATUS_WORKING", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The application configuration file contains invalid URL!.
    '''</summary>
    Friend Shared ReadOnly Property SYS_000001() As String
        Get
            Return ResourceManager.GetString("SYS-000001", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to An error has orcurred at application server..
    '''</summary>
    Friend Shared ReadOnly Property SYS_000002() As String
        Get
            Return ResourceManager.GetString("SYS-000002", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Please contact your network administrator..
    '''</summary>
    Friend Shared ReadOnly Property SYS_000003() As String
        Get
            Return ResourceManager.GetString("SYS-000003", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The remote server is unreachable..
    '''</summary>
    Friend Shared ReadOnly Property SYS_000004() As String
        Get
            Return ResourceManager.GetString("SYS-000004", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Please check your connection and try again..
    '''</summary>
    Friend Shared ReadOnly Property SYS_000005() As String
        Get
            Return ResourceManager.GetString("SYS-000005", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The username or password is incorrect..
    '''</summary>
    Friend Shared ReadOnly Property SYS_000006() As String
        Get
            Return ResourceManager.GetString("SYS-000006", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Please re-type your information!.
    '''</summary>
    Friend Shared ReadOnly Property SYS_000007() As String
        Get
            Return ResourceManager.GetString("SYS-000007", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to An unknown error has orcurred..
    '''</summary>
    Friend Shared ReadOnly Property SYS_000008() As String
        Get
            Return ResourceManager.GetString("SYS-000008", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Please review the event log for more information..
    '''</summary>
    Friend Shared ReadOnly Property SYS_000009() As String
        Get
            Return ResourceManager.GetString("SYS-000009", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to You must input username and password !.
    '''</summary>
    Friend Shared ReadOnly Property The_username_and_password_must_be_supplied() As String
        Get
            Return ResourceManager.GetString("The_username_and_password_must_be_supplied", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Enter transaction code:.
    '''</summary>
    Friend Shared ReadOnly Property TRANSACTION_CODE() As String
        Get
            Return ResourceManager.GetString("TRANSACTION_CODE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The requested function is invalid!.
    '''</summary>
    Friend Shared ReadOnly Property TransViaGenaralView() As String
        Get
            Return ResourceManager.GetString("TransViaGenaralView", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Entire word.
    '''</summary>
    Friend Shared ReadOnly Property WHOLE_WORD() As String
        Get
            Return ResourceManager.GetString("WHOLE_WORD", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Appear.
    '''</summary>
    Friend Shared ReadOnly Property WORD_APPEAR() As String
        Get
            Return ResourceManager.GetString("WORD_APPEAR", resourceCulture)
        End Get
    End Property
End Class
