'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class Localize_VN
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager(gc_RootNamespace & "." & "Localize-VN", GetType(Localize_VN).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tìm tất cả!.
    '''</summary>
    Friend Shared ReadOnly Property ___() As String
        Get
            Return ResourceManager.GetString("   ", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Bạn muốn bắt đầu ngày làm việc cho chi nhánh?.
    '''</summary>
    Friend Shared ReadOnly Property ACTIVE_BDS_CONFIRMATION() As String
        Get
            Return ResourceManager.GetString("ACTIVE_BDS_CONFIRMATION", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Bạn muốn bắt đầu ngày làm việc cho hội sở?.
    '''</summary>
    Friend Shared ReadOnly Property ACTIVE_HOST_CONFIRMATION() As String
        Get
            Return ResourceManager.GetString("ACTIVE_HOST_CONFIRMATION", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Bắt đầu bằng.
    '''</summary>
    Friend Shared ReadOnly Property BEGIN_WITH() As String
        Get
            Return ResourceManager.GetString("BEGIN_WITH", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Bạn muốn chuyển ngôn ngữ hệ thống từ Tiếng Việt sang English? Bạn phải khởi động lại ứng dụng sau khi chuyển!.
    '''</summary>
    Friend Shared ReadOnly Property CHANGE_LANGUAGE_CONFIRMATION() As String
        Get
            Return ResourceManager.GetString("CHANGE_LANGUAGE_CONFIRMATION", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Bạn muốn đóng ngày làm việc cho chi nhánh?.
    '''</summary>
    Friend Shared ReadOnly Property DEACTIVE_BDS_CONFIRMATION() As String
        Get
            Return ResourceManager.GetString("DEACTIVE_BDS_CONFIRMATION", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Bạn muốn đóng ngày làm việc cho hội sở?.
    '''</summary>
    Friend Shared ReadOnly Property DEACTIVE_HOST_CONFIRMATION() As String
        Get
            Return ResourceManager.GetString("DEACTIVE_HOST_CONFIRMATION", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to --Tất cả--.
    '''</summary>
    Friend Shared ReadOnly Property DURATION_ALL() As String
        Get
            Return ResourceManager.GetString("DURATION_ALL", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Từ ngày ... đến ngày ....
    '''</summary>
    Friend Shared ReadOnly Property DURATION_FROM_DATE_TO_DATE() As String
        Get
            Return ResourceManager.GetString("DURATION_FROM_DATE_TO_DATE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to 2 tuần trước.
    '''</summary>
    Friend Shared ReadOnly Property DURATION_LAST_2_WEEK() As String
        Get
            Return ResourceManager.GetString("DURATION_LAST_2_WEEK", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to 3 tháng trước.
    '''</summary>
    Friend Shared ReadOnly Property DURATION_LAST_3_MONTH() As String
        Get
            Return ResourceManager.GetString("DURATION_LAST_3_MONTH", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to 30 ngày trước.
    '''</summary>
    Friend Shared ReadOnly Property DURATION_LAST_30_DAYS() As String
        Get
            Return ResourceManager.GetString("DURATION_LAST_30_DAYS", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to 4 tuần trước.
    '''</summary>
    Friend Shared ReadOnly Property DURATION_LAST_4_WEEK() As String
        Get
            Return ResourceManager.GetString("DURATION_LAST_4_WEEK", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to 6 tháng trước.
    '''</summary>
    Friend Shared ReadOnly Property DURATION_LAST_6_MONTH() As String
        Get
            Return ResourceManager.GetString("DURATION_LAST_6_MONTH", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Trong tháng.
    '''</summary>
    Friend Shared ReadOnly Property DURATION_MONTH() As String
        Get
            Return ResourceManager.GetString("DURATION_MONTH", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Đến ngày ....
    '''</summary>
    Friend Shared ReadOnly Property DURATION_TO_DATE() As String
        Get
            Return ResourceManager.GetString("DURATION_TO_DATE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Trong ngày.
    '''</summary>
    Friend Shared ReadOnly Property DURATION_TODATE() As String
        Get
            Return ResourceManager.GetString("DURATION_TODATE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Trong tuần.
    '''</summary>
    Friend Shared ReadOnly Property DURATION_WEEK() As String
        Get
            Return ResourceManager.GetString("DURATION_WEEK", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Trong năm.
    '''</summary>
    Friend Shared ReadOnly Property DURATION_YEAR() As String
        Get
            Return ResourceManager.GetString("DURATION_YEAR", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Kết thúc bằng.
    '''</summary>
    Friend Shared ReadOnly Property END_WITH() As String
        Get
            Return ResourceManager.GetString("END_WITH", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Bạn muốn thoát khỏi chương trình?.
    '''</summary>
    Friend Shared ReadOnly Property EXIT_CONFIRMATION() As String
        Get
            Return ResourceManager.GetString("EXIT_CONFIRMATION", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Trợ giúp.
    '''</summary>
    Friend Shared ReadOnly Property frmMDIMain_mnuHelp() As String
        Get
            Return ResourceManager.GetString("frmMDIMain.mnuHelp", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Thông tin chương trình....
    '''</summary>
    Friend Shared ReadOnly Property frmMDIMain_mnuHelpAbout() As String
        Get
            Return ResourceManager.GetString("frmMDIMain.mnuHelpAbout", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Hướng dẫn sử dụng.
    '''</summary>
    Friend Shared ReadOnly Property frmMDIMain_mnuHelpUserManual() As String
        Get
            Return ResourceManager.GetString("frmMDIMain.mnuHelpUserManual", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to English.
    '''</summary>
    Friend Shared ReadOnly Property frmMDIMain_mnuLangEnglish() As String
        Get
            Return ResourceManager.GetString("frmMDIMain.mnuLangEnglish", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Ngôn ngữ.
    '''</summary>
    Friend Shared ReadOnly Property frmMDIMain_mnuLanguage() As String
        Get
            Return ResourceManager.GetString("frmMDIMain.mnuLanguage", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tiếng Việt.
    '''</summary>
    Friend Shared ReadOnly Property frmMDIMain_mnuLangVietnamese() As String
        Get
            Return ResourceManager.GetString("frmMDIMain.mnuLangVietnamese", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Hệ thống.
    '''</summary>
    Friend Shared ReadOnly Property frmMDIMain_mnuSys() As String
        Get
            Return ResourceManager.GetString("frmMDIMain.mnuSys", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Đổi mật khẩu....
    '''</summary>
    Friend Shared ReadOnly Property frmMDIMain_mnuSysChangePassword() As String
        Get
            Return ResourceManager.GetString("frmMDIMain.mnuSysChangePassword", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Thoát khỏi chương trình.
    '''</summary>
    Friend Shared ReadOnly Property frmMDIMain_mnuSysExit() As String
        Get
            Return ResourceManager.GetString("frmMDIMain.mnuSysExit", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Vào hệ thống.
    '''</summary>
    Friend Shared ReadOnly Property frmMDIMain_mnuSysLogin() As String
        Get
            Return ResourceManager.GetString("frmMDIMain.mnuSysLogin", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Ra khỏi hệ thống.
    '''</summary>
    Friend Shared ReadOnly Property frmMDIMain_mnuSysLogout() As String
        Get
            Return ResourceManager.GetString("frmMDIMain.mnuSysLogout", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Chi nhánh.
    '''</summary>
    Friend Shared ReadOnly Property frmMDIMain_sbrPanelBranch() As String
        Get
            Return ResourceManager.GetString("frmMDIMain.sbrPanelBranch", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Ngày, giờ hệ thống.
    '''</summary>
    Friend Shared ReadOnly Property frmMDIMain_sbrPanelDateTime() As String
        Get
            Return ResourceManager.GetString("frmMDIMain.sbrPanelDateTime", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Trạng thái.
    '''</summary>
    Friend Shared ReadOnly Property frmMDIMain_sbrPanelStatus() As String
        Get
            Return ResourceManager.GetString("frmMDIMain.sbrPanelStatus", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Người sử dụng.
    '''</summary>
    Friend Shared ReadOnly Property frmMDIMain_sbrPanelUser() As String
        Get
            Return ResourceManager.GetString("frmMDIMain.sbrPanelUser", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Bạn muốn ra khỏi chương trình?.
    '''</summary>
    Friend Shared ReadOnly Property LOGOUT_CONFIRMATION() As String
        Get
            Return ResourceManager.GetString("LOGOUT_CONFIRMATION", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Chương trình sẽ cập nhật bảng mới,nhấn OK tiếp tục..
    '''</summary>
    Friend Shared ReadOnly Property MSG_APPUPDATE() As String
        Get
            Return ResourceManager.GetString("MSG_APPUPDATE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Vui lòng chọn đường dẫn đến file.xsl cần đọc!.
    '''</summary>
    Friend Shared ReadOnly Property MSG_FILEPATH() As String
        Get
            Return ResourceManager.GetString("MSG_FILEPATH", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Chương trình tự động cập nhật báo cáo mới
    '''Phiên bản báo cáo hiện tại: {0}
    '''Phiên bản báo cáo mới nhất: {1}
    '''Nhấn OK tiếp tục..
    '''</summary>
    Friend Shared ReadOnly Property MSG_UPDATESRPTRING() As String
        Get
            Return ResourceManager.GetString("MSG_UPDATESRPTRING", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Chương trình tự động cập nhật bản mới
    '''Phiên bản hiện tại: {0}
    '''Phiên bản mới nhất: {1}
    '''Nhấn OK tiếp tục..
    '''</summary>
    Friend Shared ReadOnly Property MSG_UPDATESTRING() As String
        Get
            Return ResourceManager.GetString("MSG_UPDATESTRING", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Bạn không có quyền thực hiện giao dịch này, liên hệ quản trị hệ thống !.
    '''</summary>
    Friend Shared ReadOnly Property NotAllowTrans() As String
        Get
            Return ResourceManager.GetString("NotAllowTrans", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tìm tất cả !.
    '''</summary>
    Friend Shared ReadOnly Property SEARCH_MSG_ALL() As String
        Get
            Return ResourceManager.GetString("SEARCH_MSG_ALL", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tìm theo điều kiện!.
    '''</summary>
    Friend Shared ReadOnly Property SEARCH_MSG_CONDITION() As String
        Get
            Return ResourceManager.GetString("SEARCH_MSG_CONDITION", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Xin lỗi quý vị, hiện tại chức năng này chưa được xây dựng!.
    '''</summary>
    Friend Shared ReadOnly Property SRRFunctionNotBuild() As String
        Get
            Return ResourceManager.GetString("SRRFunctionNotBuild", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Đang khởi tạo cây menu. Xin vui lòng chờ trong giây lát....
    '''</summary>
    Friend Shared ReadOnly Property STATUS_LOADING_MENU() As String
        Get
            Return ResourceManager.GetString("STATUS_LOADING_MENU", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Đang khởi tạo các tham số hệ thống. Xin vui lòng chờ trong giây lát....
    '''</summary>
    Friend Shared ReadOnly Property STATUS_LOADING_PARAMS() As String
        Get
            Return ResourceManager.GetString("STATUS_LOADING_PARAMS", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Đang làm việc trong hệ thống..
    '''</summary>
    Friend Shared ReadOnly Property STATUS_WORKING() As String
        Get
            Return ResourceManager.GetString("STATUS_WORKING", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to File cấu hình của ứng dụng chứa URL không hợp lệ!.
    '''</summary>
    Friend Shared ReadOnly Property SYS_000001() As String
        Get
            Return ResourceManager.GetString("SYS-000001", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Lỗi tại máy chủ ứng dụng..
    '''</summary>
    Friend Shared ReadOnly Property SYS_000002() As String
        Get
            Return ResourceManager.GetString("SYS-000002", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Hãy liên hệ với quản trị hệ thống..
    '''</summary>
    Friend Shared ReadOnly Property SYS_000003() As String
        Get
            Return ResourceManager.GetString("SYS-000003", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Không kết nối được đến máy chủ ứng dụng..
    '''</summary>
    Friend Shared ReadOnly Property SYS_000004() As String
        Get
            Return ResourceManager.GetString("SYS-000004", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Hãy kiểm tra kết nối đến máy chủ ứng dụng và thử lại..
    '''</summary>
    Friend Shared ReadOnly Property SYS_000005() As String
        Get
            Return ResourceManager.GetString("SYS-000005", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Mã truy cập hoặc mật khẩu không hợp lệ.
    '''
    '''.
    '''</summary>
    Friend Shared ReadOnly Property SYS_000006() As String
        Get
            Return ResourceManager.GetString("SYS-000006", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Vui lòng nhập lại thông tin!.
    '''</summary>
    Friend Shared ReadOnly Property SYS_000007() As String
        Get
            Return ResourceManager.GetString("SYS-000007", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Lỗi không xác định..
    '''</summary>
    Friend Shared ReadOnly Property SYS_000008() As String
        Get
            Return ResourceManager.GetString("SYS-000008", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Kiểm tra event log để biết thông tin chi tiết..
    '''</summary>
    Friend Shared ReadOnly Property SYS_000009() As String
        Get
            Return ResourceManager.GetString("SYS-000009", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Bạn phải nhập vào mã truy cập và mật khẩu!.
    '''</summary>
    Friend Shared ReadOnly Property The_username_and_password_must_be_supplied() As String
        Get
            Return ResourceManager.GetString("The_username_and_password_must_be_supplied", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Mã giao dịch:.
    '''</summary>
    Friend Shared ReadOnly Property TRANSACTION_CODE() As String
        Get
            Return ResourceManager.GetString("TRANSACTION_CODE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Chức năng không tồn tại, không được gọi trực tiếp hoặc bạn không đủ quyền sử dụng chức năng này!.
    '''</summary>
    Friend Shared ReadOnly Property TransViaGenaralView() As String
        Get
            Return ResourceManager.GetString("TransViaGenaralView", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Đúng bằng.
    '''</summary>
    Friend Shared ReadOnly Property WHOLE_WORD() As String
        Get
            Return ResourceManager.GetString("WHOLE_WORD", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Có xuất hiện.
    '''</summary>
    Friend Shared ReadOnly Property WORD_APPEAR() As String
        Get
            Return ResourceManager.GetString("WORD_APPEAR", resourceCulture)
        End Get
    End Property
End Class
