'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class frmBatch_EN
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("AppCore.frmBatch-EN", GetType(frmBatch_EN).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Execute failed.
    '''</summary>
    Friend Shared ReadOnly Property BATCH_RUN_FAILED() As String
        Get
            Return ResourceManager.GetString("BATCH_RUN_FAILED", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Execute successfully.
    '''</summary>
    Friend Shared ReadOnly Property BATCH_RUN_SUCCESS() As String
        Get
            Return ResourceManager.GetString("BATCH_RUN_SUCCESS", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Check all.
    '''</summary>
    Friend Shared ReadOnly Property chkCheckAll() As String
        Get
            Return ResourceManager.GetString("chkCheckAll", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Please enter CONFIRM in the textbox!.
    '''</summary>
    Friend Shared ReadOnly Property CONFIRM() As String
        Get
            Return ResourceManager.GetString("CONFIRM", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to done.
    '''</summary>
    Friend Shared ReadOnly Property done() As String
        Get
            Return ResourceManager.GetString("done", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to successful.
    '''</summary>
    Friend Shared ReadOnly Property donepage() As String
        Get
            Return ResourceManager.GetString("donepage", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to failed.
    '''</summary>
    Friend Shared ReadOnly Property failed() As String
        Get
            Return ResourceManager.GetString("failed", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to failed at page .
    '''</summary>
    Friend Shared ReadOnly Property failedatpage() As String
        Get
            Return ResourceManager.GetString("failedatpage", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to End of day processing.
    '''</summary>
    Friend Shared ReadOnly Property frmBatch() As String
        Get
            Return ResourceManager.GetString("frmBatch", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Close.
    '''</summary>
    Friend Shared ReadOnly Property frmBatch_btnCancel() As String
        Get
            Return ResourceManager.GetString("frmBatch.btnCancel", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Execute.
    '''</summary>
    Friend Shared ReadOnly Property frmBatch_btnOK() As String
        Get
            Return ResourceManager.GetString("frmBatch.btnOK", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Confirm.
    '''</summary>
    Friend Shared ReadOnly Property frmBatch_lblConfirm() As String
        Get
            Return ResourceManager.GetString("frmBatch.lblConfirm", resourceCulture)
        End Get
    End Property
End Class
