'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class frmMaster_EN
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("AppCore.frmMaster-EN", GetType(frmMaster_EN).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Add new @ successfully.
    '''</summary>
    Friend Shared ReadOnly Property AddSuccess() As String
        Get
            Return ResourceManager.GetString("AddSuccess", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Bạn có chắc chắn muốn duyệt bảng kê?.
    '''</summary>
    Friend Shared ReadOnly Property ApproveConfirm() As String
        Get
            Return ResourceManager.GetString("ApproveConfirm", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Approve data successfull.
    '''</summary>
    Friend Shared ReadOnly Property ApproveSuccessful() As String
        Get
            Return ResourceManager.GetString("ApproveSuccessful", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Apply.
    '''</summary>
    Friend Shared ReadOnly Property btnApply() As String
        Get
            Return ResourceManager.GetString("btnApply", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Approve.
    '''</summary>
    Friend Shared ReadOnly Property btnApprove() As String
        Get
            Return ResourceManager.GetString("btnApprove", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Close.
    '''</summary>
    Friend Shared ReadOnly Property btnCancel() As String
        Get
            Return ResourceManager.GetString("btnCancel", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;External.
    '''</summary>
    Friend Shared ReadOnly Property btnExternal() As String
        Get
            Return ResourceManager.GetString("btnExternal", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Navigate.
    '''</summary>
    Friend Shared ReadOnly Property btnNavigate() As String
        Get
            Return ResourceManager.GetString("btnNavigate", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;OK.
    '''</summary>
    Friend Shared ReadOnly Property btnOK() As String
        Get
            Return ResourceManager.GetString("btnOK", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Reject.
    '''</summary>
    Friend Shared ReadOnly Property btnReject() As String
        Get
            Return ResourceManager.GetString("btnReject", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Delete.
    '''</summary>
    Friend Shared ReadOnly Property btnSubDelete() As String
        Get
            Return ResourceManager.GetString("btnSubDelete", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Edit.
    '''</summary>
    Friend Shared ReadOnly Property btnSubEdit() As String
        Get
            Return ResourceManager.GetString("btnSubEdit", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Export.
    '''</summary>
    Friend Shared ReadOnly Property btnSubExport() As String
        Get
            Return ResourceManager.GetString("btnSubExport", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to First.
    '''</summary>
    Friend Shared ReadOnly Property btnSubFirst() As String
        Get
            Return ResourceManager.GetString("btnSubFirst", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Insert.
    '''</summary>
    Friend Shared ReadOnly Property btnSubInsert() As String
        Get
            Return ResourceManager.GetString("btnSubInsert", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Last.
    '''</summary>
    Friend Shared ReadOnly Property btnSubLast() As String
        Get
            Return ResourceManager.GetString("btnSubLast", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Next.
    '''</summary>
    Friend Shared ReadOnly Property btnSubNext() As String
        Get
            Return ResourceManager.GetString("btnSubNext", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Previous.
    '''</summary>
    Friend Shared ReadOnly Property btnSubPrevious() As String
        Get
            Return ResourceManager.GetString("btnSubPrevious", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Refresh.
    '''</summary>
    Friend Shared ReadOnly Property btnSubRefresh() As String
        Get
            Return ResourceManager.GetString("btnSubRefresh", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to View.
    '''</summary>
    Friend Shared ReadOnly Property btnSubView() As String
        Get
            Return ResourceManager.GetString("btnSubView", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Create new information:.
    '''</summary>
    Friend Shared ReadOnly Property CaptionAdd() As String
        Get
            Return ResourceManager.GetString("CaptionAdd", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Change current information.
    '''</summary>
    Friend Shared ReadOnly Property CaptionEdit() As String
        Get
            Return ResourceManager.GetString("CaptionEdit", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to View current information.
    '''</summary>
    Friend Shared ReadOnly Property CaptionView() As String
        Get
            Return ResourceManager.GetString("CaptionView", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Do you want to delete all selected data?.
    '''</summary>
    Friend Shared ReadOnly Property DelConfirm() As String
        Get
            Return ResourceManager.GetString("DelConfirm", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The information for @ is deleted successfully.
    '''</summary>
    Friend Shared ReadOnly Property DeleteSuccess() As String
        Get
            Return ResourceManager.GetString("DeleteSuccess", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Change the information for @ successfully.
    '''</summary>
    Friend Shared ReadOnly Property EditSuccess() As String
        Get
            Return ResourceManager.GetString("EditSuccess", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Bank account  not link with PHS.
    '''</summary>
    Friend Shared ReadOnly Property ERR_CFOTHERACC_BANKACC_NOT_LINK() As String
        Get
            Return ResourceManager.GetString("ERR_CFOTHERACC_BANKACC_NOT_LINK", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Receive customer is different from send customer!.
    '''</summary>
    Friend Shared ReadOnly Property ERR_CFOTHERACC_DIFFERENCE_INFO() As String
        Get
            Return ResourceManager.GetString("ERR_CFOTHERACC_DIFFERENCE_INFO", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to @: The value @ isn&apos;t true!.
    '''</summary>
    Friend Shared ReadOnly Property ERR_COMBOBOX_SELECTVALUE() As String
        Get
            Return ResourceManager.GetString("ERR_COMBOBOX_SELECTVALUE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to @: The date value is invalid.
    '''</summary>
    Friend Shared ReadOnly Property ERR_DATE_VALUE() As String
        Get
            Return ResourceManager.GetString("ERR_DATE_VALUE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Not allowed to change information while browsing on hold!.
    '''</summary>
    Friend Shared ReadOnly Property ERR_INVALID_STATUS_01() As String
        Get
            Return ResourceManager.GetString("ERR_INVALID_STATUS_01", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Already exists a stage done right the same type and the same stocks closing date. Do you want to continue to add new one? (Press &lt;OK&gt; to continue to add new, &lt;CANCEL&gt; to exit).
    '''</summary>
    Friend Shared ReadOnly Property ERR_INVALID_STATUS_02() As String
        Get
            Return ResourceManager.GetString("ERR_INVALID_STATUS_02", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to @: The  value is invalid.
    '''</summary>
    Friend Shared ReadOnly Property ERR_INVALID_VALUE() As String
        Get
            Return ResourceManager.GetString("ERR_INVALID_VALUE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to @: The value is not in list.
    '''</summary>
    Friend Shared ReadOnly Property ERR_LOOKUP_VALUE() As String
        Get
            Return ResourceManager.GetString("ERR_LOOKUP_VALUE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to @: The field is mandatory.
    '''</summary>
    Friend Shared ReadOnly Property ERR_MANDATORY_FIELD() As String
        Get
            Return ResourceManager.GetString("ERR_MANDATORY_FIELD", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to @: The numeric value is invalid.
    '''</summary>
    Friend Shared ReadOnly Property ERR_NUMERIC_VALUE() As String
        Get
            Return ResourceManager.GetString("ERR_NUMERIC_VALUE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to @: Too big value for numeric field.
    '''</summary>
    Friend Shared ReadOnly Property ERR_OVER_DBL_VALUE() As String
        Get
            Return ResourceManager.GetString("ERR_OVER_DBL_VALUE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Add new.
    '''</summary>
    Friend Shared ReadOnly Property ExecuteFlag_AddNew() As String
        Get
            Return ResourceManager.GetString("ExecuteFlag.AddNew", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Delete.
    '''</summary>
    Friend Shared ReadOnly Property ExecuteFlag_Delete() As String
        Get
            Return ResourceManager.GetString("ExecuteFlag.Delete", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Edit.
    '''</summary>
    Friend Shared ReadOnly Property ExecuteFlag_Edit() As String
        Get
            Return ResourceManager.GetString("ExecuteFlag.Edit", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;View.
    '''</summary>
    Friend Shared ReadOnly Property ExecuteFlag_View() As String
        Get
            Return ResourceManager.GetString("ExecuteFlag.View", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Maintainance screen.
    '''</summary>
    Friend Shared ReadOnly Property frmMaster() As String
        Get
            Return ResourceManager.GetString("frmMaster", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Export data successful!.
    '''</summary>
    Friend Shared ReadOnly Property frmMaster_ExportSuccessful() As String
        Get
            Return ResourceManager.GetString("frmMaster.ExportSuccessful", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to There is nothing to export!.
    '''</summary>
    Friend Shared ReadOnly Property frmMaster_NothingToExport() As String
        Get
            Return ResourceManager.GetString("frmMaster.NothingToExport", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Initialize dialog is failded.
    '''</summary>
    Friend Shared ReadOnly Property InitDialogFailed() As String
        Get
            Return ResourceManager.GetString("InitDialogFailed", resourceCulture)
        End Get
    End Property
End Class
