'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class frmReportParameter_VN
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("AppCore.frmReportParameter-VN", GetType(frmReportParameter_VN).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Mã lưu ký không hợp lệ.
    '''</summary>
    Friend Shared ReadOnly Property ERR_CUSTODYCD_INVALID_PCFLAG_PC() As String
        Get
            Return ResourceManager.GetString("ERR_CUSTODYCD_INVALID_PCFLAG_PC", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The field [@] data is invalid. Press F5 key and select valid data!.
    '''</summary>
    Friend Shared ReadOnly Property ERR_DATA_NOTFOUND() As String
        Get
            Return ResourceManager.GetString("ERR_DATA_NOTFOUND", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Những khách hàng này không được đăng ký tạo báo cáo theo lô !.
    '''</summary>
    Friend Shared ReadOnly Property ERR001() As String
        Get
            Return ResourceManager.GetString("ERR001", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Thoát.
    '''</summary>
    Friend Shared ReadOnly Property frmReportParameter_btnCANCEL() As String
        Get
            Return ResourceManager.GetString("frmReportParameter.btnCANCEL", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Đối chiếu.
    '''</summary>
    Friend Shared ReadOnly Property frmReportParameter_btnCMP() As String
        Get
            Return ResourceManager.GetString("frmReportParameter.btnCMP", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tải về.
    '''</summary>
    Friend Shared ReadOnly Property frmReportParameter_btnDownload() As String
        Get
            Return ResourceManager.GetString("frmReportParameter.btnDownload", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Chấp nhận.
    '''</summary>
    Friend Shared ReadOnly Property frmReportParameter_btnOK() As String
        Get
            Return ResourceManager.GetString("frmReportParameter.btnOK", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Từ ngày lớn hơn đến ngày!.
    '''</summary>
    Friend Shared ReadOnly Property frmReportParameter_date() As String
        Get
            Return ResourceManager.GetString("frmReportParameter.date", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Trường [@] không hợp lệ..
    '''</summary>
    Friend Shared ReadOnly Property frmReportParameter_DateInvalid() As String
        Get
            Return ResourceManager.GetString("frmReportParameter.DateInvalid", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Xuất dữ liệu thành công !.
    '''</summary>
    Friend Shared ReadOnly Property frmReportParameter_ExportSucessfully() As String
        Get
            Return ResourceManager.GetString("frmReportParameter.ExportSucessfully", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to File mẫu báo cáo không tồn tại!.
    '''</summary>
    Friend Shared ReadOnly Property frmReportParameter_FileNotExists() As String
        Get
            Return ResourceManager.GetString("frmReportParameter.FileNotExists", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to $CMDID : $REPORTTITLE .
    '''</summary>
    Friend Shared ReadOnly Property frmReportParameter_frmReportParameter() As String
        Get
            Return ResourceManager.GetString("frmReportParameter.frmReportParameter", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Trường [@] không hợp lệ. Bấm phím F5 để lựa chọn giá trị từ danh sách!.
    '''</summary>
    Friend Shared ReadOnly Property frmReportParameter_InvalidData() As String
        Get
            Return ResourceManager.GetString("frmReportParameter.InvalidData", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Nhập các tham số và chọn nút &lt;Chấp nhận&gt; để tạo báo cáo..
    '''</summary>
    Friend Shared ReadOnly Property frmReportParameter_lblCaption() As String
        Get
            Return ResourceManager.GetString("frmReportParameter.lblCaption", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Không có dữ liệu cho  báo cáo!.
    '''</summary>
    Friend Shared ReadOnly Property frmReportParameter_Nodata() As String
        Get
            Return ResourceManager.GetString("frmReportParameter.Nodata", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Bạn không quản lý khách hàng này!.
    '''</summary>
    Friend Shared ReadOnly Property frmReportParameter_NotCareBy() As String
        Get
            Return ResourceManager.GetString("frmReportParameter.NotCareBy", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Yêu cầu tạo báo cáo đang được chờ xử lý !.
    '''</summary>
    Friend Shared ReadOnly Property frmReportParameter_Pending() As String
        Get
            Return ResourceManager.GetString("frmReportParameter.Pending", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tạo báo cáo thành công!.
    '''</summary>
    Friend Shared ReadOnly Property frmReportParameter_ReCreateSucessfully() As String
        Get
            Return ResourceManager.GetString("frmReportParameter.ReCreateSucessfully", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Phạm vi (area).
    '''</summary>
    Friend Shared ReadOnly Property frmReportParameter_ReportArea() As String
        Get
            Return ResourceManager.GetString("frmReportParameter.ReportArea", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Đại lý (agent).
    '''</summary>
    Friend Shared ReadOnly Property frmReportParameter_ReportArea_Agent() As String
        Get
            Return ResourceManager.GetString("frmReportParameter.ReportArea.Agent", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Toàn công ty (company).
    '''</summary>
    Friend Shared ReadOnly Property frmReportParameter_ReportArea_All() As String
        Get
            Return ResourceManager.GetString("frmReportParameter.ReportArea.All", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Chi nhánh (branch).
    '''</summary>
    Friend Shared ReadOnly Property frmReportParameter_ReportArea_Branch() As String
        Get
            Return ResourceManager.GetString("frmReportParameter.ReportArea.Branch", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Báo cáo chưa được tạo. Bạn phải tạo báo cáo trước khi xem hoặc in!.
    '''</summary>
    Friend Shared ReadOnly Property frmReportParameter_ReportNotCreated() As String
        Get
            Return ResourceManager.GetString("frmReportParameter.ReportNotCreated", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Trường [@] không được để trống!.
    '''</summary>
    Friend Shared ReadOnly Property Mandatory() As String
        Get
            Return ResourceManager.GetString("Mandatory", resourceCulture)
        End Get
    End Property
End Class
