'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class frmSearch_EN
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("AppCore.frmSearch-EN", GetType(frmSearch_EN).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;ObjectMessage TXDATE=&quot;&quot; TXNUM=&quot;&quot; TXTIME=&quot;&quot; TLID=&quot;0001&quot; BRID=&quot;0001&quot; LOCAL=&quot;N&quot; MSGTYPE=&quot;O&quot; OBJNAME=&quot;SA.EMAILSMSLOG&quot; ACTIONFLAG=&quot;ADD&quot; CMDINQUIRY=&quot;&quot; CLAUSE=&quot;&quot; FUNCTIONNAME=&quot;&quot; AUTOID=&quot;Y&quot; REFERENCE=&quot;&quot; RESERVER=&quot;&quot; IPADDRESS=&quot;&quot; CMDTYPE=&quot;T&quot; PARENTOBJNAME=&quot;&quot; PARENTCLAUSE=&quot;&quot;&gt;&lt;ObjData&gt;&lt;Entry fldname=&quot;TXDATE&quot; fldtype=&quot;System.Date&quot; oldval=&quot;[TXDATE]&quot;&gt;[TXDATE]&lt;/Entry&gt;&lt;Entry fldname=&quot;TXTIME&quot; fldtype=&quot;System.String&quot; oldval=&quot;[TXTIME]&quot;&gt;[TXTIME]&lt;/Entry&gt;&lt;Entry fldname=&quot;ACCTNO&quot; fldtype=&quot;System.String&quot; oldval=&quot;[ACCTNO]&quot;&gt;[ACCTNO]&lt; [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property EMAILLOGMESSAGE() As String
        Get
            Return ResourceManager.GetString("EMAILLOGMESSAGE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Deal không có chứng khoán sẵn sàng để bán.
    '''</summary>
    Friend Shared ReadOnly Property ERR_CANNOT_FORCE_SELL_DEAL() As String
        Get
            Return ResourceManager.GetString("ERR_CANNOT_FORCE_SELL_DEAL", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Please choose record to execute!.
    '''</summary>
    Friend Shared ReadOnly Property ERR_CHOOSE_RECORD_TO_EXECUTE() As String
        Get
            Return ResourceManager.GetString("ERR_CHOOSE_RECORD_TO_EXECUTE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Add new.
    '''</summary>
    Friend Shared ReadOnly Property ExecuteFlag_AddNew() As String
        Get
            Return ResourceManager.GetString("ExecuteFlag.AddNew", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Delete.
    '''</summary>
    Friend Shared ReadOnly Property ExecuteFlag_Delete() As String
        Get
            Return ResourceManager.GetString("ExecuteFlag.Delete", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Edit.
    '''</summary>
    Friend Shared ReadOnly Property ExecuteFlag_Edit() As String
        Get
            Return ResourceManager.GetString("ExecuteFlag.Edit", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to S&amp;MS.
    '''</summary>
    Friend Shared ReadOnly Property ExecuteFlag_SendSMS() As String
        Get
            Return ResourceManager.GetString("ExecuteFlag.SendSMS", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;View.
    '''</summary>
    Friend Shared ReadOnly Property ExecuteFlag_View() As String
        Get
            Return ResourceManager.GetString("ExecuteFlag.View", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Compare.
    '''</summary>
    Friend Shared ReadOnly Property frmSearch_bbiCompare() As String
        Get
            Return ResourceManager.GetString("frmSearch.bbiCompare", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Export.
    '''</summary>
    Friend Shared ReadOnly Property frmSearch_bbiExport() As String
        Get
            Return ResourceManager.GetString("frmSearch.bbiExport", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Hide/Show Criterial.
    '''</summary>
    Friend Shared ReadOnly Property frmSearch_bbiFullScreen() As String
        Get
            Return ResourceManager.GetString("frmSearch.bbiFullScreen", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Preview.
    '''</summary>
    Friend Shared ReadOnly Property frmSearch_bbiPreview() As String
        Get
            Return ResourceManager.GetString("frmSearch.bbiPreview", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Search.
    '''</summary>
    Friend Shared ReadOnly Property frmSearch_bbiSearch() As String
        Get
            Return ResourceManager.GetString("frmSearch.bbiSearch", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to All Page.
    '''</summary>
    Friend Shared ReadOnly Property frmSearch_bciCheckAll() As String
        Get
            Return ResourceManager.GetString("frmSearch.bciCheckAll", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Execute All.
    '''</summary>
    Friend Shared ReadOnly Property frmSearch_bciExecuteAll() As String
        Get
            Return ResourceManager.GetString("frmSearch.bciExecuteAll", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to 4.
    '''</summary>
    Friend Shared ReadOnly Property frmSearch_btnAdd() As String
        Get
            Return ResourceManager.GetString("frmSearch.btnAdd", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Back.
    '''</summary>
    Friend Shared ReadOnly Property frmSearch_btnBACK() As String
        Get
            Return ResourceManager.GetString("frmSearch.btnBACK", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Email.
    '''</summary>
    Friend Shared ReadOnly Property frmSearch_btnEmail() As String
        Get
            Return ResourceManager.GetString("frmSearch.btnEmail", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to E&amp;xport.
    '''</summary>
    Friend Shared ReadOnly Property frmSearch_btnExport() As String
        Get
            Return ResourceManager.GetString("frmSearch.btnExport", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Next.
    '''</summary>
    Friend Shared ReadOnly Property frmSearch_btnNEXT() As String
        Get
            Return ResourceManager.GetString("frmSearch.btnNEXT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to 3.
    '''</summary>
    Friend Shared ReadOnly Property frmSearch_btnRemove() As String
        Get
            Return ResourceManager.GetString("frmSearch.btnRemove", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to 7.
    '''</summary>
    Friend Shared ReadOnly Property frmSearch_btnRemoveAll() As String
        Get
            Return ResourceManager.GetString("frmSearch.btnRemoveAll", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Search.
    '''</summary>
    Friend Shared ReadOnly Property frmSearch_btnSearch() As String
        Get
            Return ResourceManager.GetString("frmSearch.btnSearch", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to S&amp;MS.
    '''</summary>
    Friend Shared ReadOnly Property frmSearch_btnSendSMS() As String
        Get
            Return ResourceManager.GetString("frmSearch.btnSendSMS", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Criterial.
    '''</summary>
    Friend Shared ReadOnly Property frmSearch_Criterial() As String
        Get
            Return ResourceManager.GetString("frmSearch.Criterial", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Are you sure to delete this data row?.
    '''</summary>
    Friend Shared ReadOnly Property frmSearch_DelConfirm() As String
        Get
            Return ResourceManager.GetString("frmSearch.DelConfirm", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Data delete successful!.
    '''</summary>
    Friend Shared ReadOnly Property frmSearch_DelSuccess() As String
        Get
            Return ResourceManager.GetString("frmSearch.DelSuccess", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Are you sure to delete this data row?.
    '''</summary>
    Friend Shared ReadOnly Property frmSearch_DisposeConfirm() As String
        Get
            Return ResourceManager.GetString("frmSearch.DisposeConfirm", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Description of delete.
    '''</summary>
    Friend Shared ReadOnly Property frmSearch_DisposeDescInput() As String
        Get
            Return ResourceManager.GetString("frmSearch.DisposeDescInput", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Logged Email successfully.
    '''</summary>
    Friend Shared ReadOnly Property frmSearch_EmailSuccess() As String
        Get
            Return ResourceManager.GetString("frmSearch.EmailSuccess", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Export data successful!.
    '''</summary>
    Friend Shared ReadOnly Property frmSearch_ExportSuccessful() As String
        Get
            Return ResourceManager.GetString("frmSearch.ExportSuccessful", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to This is the footer of result grid. Cannot view, edit or delete data!.
    '''</summary>
    Friend Shared ReadOnly Property frmSearch_Footer() As String
        Get
            Return ResourceManager.GetString("frmSearch.Footer", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Condition:.
    '''</summary>
    Friend Shared ReadOnly Property frmSearch_grbCondition() As String
        Get
            Return ResourceManager.GetString("frmSearch.grbCondition", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Condition list:.
    '''</summary>
    Friend Shared ReadOnly Property frmSearch_grbConditionList() As String
        Get
            Return ResourceManager.GetString("frmSearch.grbConditionList", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Search condition:.
    '''</summary>
    Friend Shared ReadOnly Property frmSearch_grbSearchFilter() As String
        Get
            Return ResourceManager.GetString("frmSearch.grbSearchFilter", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Search result:.
    '''</summary>
    Friend Shared ReadOnly Property frmSearch_grbSearchResult() As String
        Get
            Return ResourceManager.GetString("frmSearch.grbSearchResult", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Field:.
    '''</summary>
    Friend Shared ReadOnly Property frmSearch_lblField() As String
        Get
            Return ResourceManager.GetString("frmSearch.lblField", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Operator:.
    '''</summary>
    Friend Shared ReadOnly Property frmSearch_lblOperator() As String
        Get
            Return ResourceManager.GetString("frmSearch.lblOperator", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Value:.
    '''</summary>
    Friend Shared ReadOnly Property frmSearch_lblValue() As String
        Get
            Return ResourceManager.GetString("frmSearch.lblValue", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Must enter the format of the output file!.
    '''</summary>
    Friend Shared ReadOnly Property frmSearch_NothingExtension() As String
        Get
            Return ResourceManager.GetString("frmSearch.NothingExtension", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to No data to compare!.
    '''</summary>
    Friend Shared ReadOnly Property frmSearch_NothingToCompare() As String
        Get
            Return ResourceManager.GetString("frmSearch.NothingToCompare", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to There is nothing to export!.
    '''</summary>
    Friend Shared ReadOnly Property frmSearch_NothingToExport() As String
        Get
            Return ResourceManager.GetString("frmSearch.NothingToExport", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Nothing to print.
    '''</summary>
    Friend Shared ReadOnly Property frmSearch_NothingToPrint() As String
        Get
            Return ResourceManager.GetString("frmSearch.NothingToPrint", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to You must select row of data to view, edit or delete!.
    '''</summary>
    Friend Shared ReadOnly Property frmSearch_NotSelected() As String
        Get
            Return ResourceManager.GetString("frmSearch.NotSelected", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Searching....
    '''</summary>
    Friend Shared ReadOnly Property frmSearch_Searching() As String
        Get
            Return ResourceManager.GetString("frmSearch.Searching", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Search Results.
    '''</summary>
    Friend Shared ReadOnly Property frmSearch_SearchResults() As String
        Get
            Return ResourceManager.GetString("frmSearch.SearchResults", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Logged SMS successfully.
    '''</summary>
    Friend Shared ReadOnly Property frmSearch_SMSSuccess() As String
        Get
            Return ResourceManager.GetString("frmSearch.SMSSuccess", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Add.
    '''</summary>
    Friend Shared ReadOnly Property frmSearch_tbnAdd() As String
        Get
            Return ResourceManager.GetString("frmSearch.tbnAdd", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to A&amp;pprove.
    '''</summary>
    Friend Shared ReadOnly Property frmSearch_tbnApprove() As String
        Get
            Return ResourceManager.GetString("frmSearch.tbnApprove", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Compare.
    '''</summary>
    Friend Shared ReadOnly Property frmSearch_tbnCompare() As String
        Get
            Return ResourceManager.GetString("frmSearch.tbnCompare", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Delete.
    '''</summary>
    Friend Shared ReadOnly Property frmSearch_tbnDelete() As String
        Get
            Return ResourceManager.GetString("frmSearch.tbnDelete", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Delete.
    '''</summary>
    Friend Shared ReadOnly Property frmSearch_tbnDispose() As String
        Get
            Return ResourceManager.GetString("frmSearch.tbnDispose", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Change ST.
    '''</summary>
    Friend Shared ReadOnly Property frmSearch_tbnDisposeC() As String
        Get
            Return ResourceManager.GetString("frmSearch.tbnDisposeC", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Edit.
    '''</summary>
    Friend Shared ReadOnly Property frmSearch_tbnEdit() As String
        Get
            Return ResourceManager.GetString("frmSearch.tbnEdit", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Execute.
    '''</summary>
    Friend Shared ReadOnly Property frmSearch_tbnExecute() As String
        Get
            Return ResourceManager.GetString("frmSearch.tbnExecute", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Close.
    '''</summary>
    Friend Shared ReadOnly Property frmSearch_tbnExit() As String
        Get
            Return ResourceManager.GetString("frmSearch.tbnExit", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Print.
    '''</summary>
    Friend Shared ReadOnly Property frmSearch_tbnPrint() As String
        Get
            Return ResourceManager.GetString("frmSearch.tbnPrint", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;View.
    '''</summary>
    Friend Shared ReadOnly Property frmSearch_tbnView() As String
        Get
            Return ResourceManager.GetString("frmSearch.tbnView", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Sum of records: .
    '''</summary>
    Friend Shared ReadOnly Property GridEx_FooterRow() As String
        Get
            Return ResourceManager.GetString("GridEx.FooterRow", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to From row .
    '''</summary>
    Friend Shared ReadOnly Property GridEx_FooterRowFrom() As String
        Get
            Return ResourceManager.GetString("GridEx.FooterRowFrom", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to in @ row(s)..
    '''</summary>
    Friend Shared ReadOnly Property GridEx_FooterRowIn() As String
        Get
            Return ResourceManager.GetString("GridEx.FooterRowIn", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to to row .
    '''</summary>
    Friend Shared ReadOnly Property GridEx_FooterRowTo() As String
        Get
            Return ResourceManager.GetString("GridEx.FooterRowTo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Drag and drop column which should be grouped! (F6: Focus to grid).
    '''</summary>
    Friend Shared ReadOnly Property GridEx_GroupByRow() As String
        Get
            Return ResourceManager.GetString("GridEx.GroupByRow", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Mr/Mrs: &lt;&lt;FULLNAME&gt;&gt;  is Issuer Member.
    '''</summary>
    Friend Shared ReadOnly Property ISSUER_MEMBER() As String
        Get
            Return ResourceManager.GetString("ISSUER_MEMBER", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Filter fields request: .
    '''</summary>
    Friend Shared ReadOnly Property REQUIRE_SEARCHFILTER() As String
        Get
            Return ResourceManager.GetString("REQUIRE_SEARCHFILTER", resourceCulture)
        End Get
    End Property
End Class
