'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class frmSearchCMP2FILE_VN
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("AppCore.frmSearchCMP2FILE-VN", GetType(frmSearchCMP2FILE_VN).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to ....
    '''</summary>
    Friend Shared ReadOnly Property btnBrowser() As String
        Get
            Return ResourceManager.GetString("btnBrowser", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Thoát.
    '''</summary>
    Friend Shared ReadOnly Property btnCancel() As String
        Get
            Return ResourceManager.GetString("btnCancel", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Đối chiếu.
    '''</summary>
    Friend Shared ReadOnly Property btnCompare() As String
        Get
            Return ResourceManager.GetString("btnCompare", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Kết xuất.
    '''</summary>
    Friend Shared ReadOnly Property btnExport() As String
        Get
            Return ResourceManager.GetString("btnExport", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Choose VSD File.
    '''</summary>
    Friend Shared ReadOnly Property btnFileCSV() As String
        Get
            Return ResourceManager.GetString("btnFileCSV", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to ....
    '''</summary>
    Friend Shared ReadOnly Property btnOpenFile() As String
        Get
            Return ResourceManager.GetString("btnOpenFile", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Đối chiếu dữ liệu.
    '''</summary>
    Friend Shared ReadOnly Property frmSearchCMP2FILE() As String
        Get
            Return ResourceManager.GetString("frmSearchCMP2FILE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Đã có lỗi xảy ra khi chuyển dữ liệu !.
    '''</summary>
    Friend Shared ReadOnly Property frmSearchCMP2FILE_CannotImportToDB() As String
        Get
            Return ResourceManager.GetString("frmSearchCMP2FILE.CannotImportToDB", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Không mở được file dữ liệu !.
    '''</summary>
    Friend Shared ReadOnly Property frmSearchCMP2FILE_CannotOpenFile() As String
        Get
            Return ResourceManager.GetString("frmSearchCMP2FILE.CannotOpenFile", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Kết xuất dữ liệu thành công!.
    '''</summary>
    Friend Shared ReadOnly Property frmSearchCMP2FILE_ExportSuccessful() As String
        Get
            Return ResourceManager.GetString("frmSearchCMP2FILE.ExportSuccessful", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Dữ liệu trên file và hệ thống trùng khớp nhau!.
    '''</summary>
    Friend Shared ReadOnly Property frmSearchCMP2FILE_FILE_SAME_DATA() As String
        Get
            Return ResourceManager.GetString("frmSearchCMP2FILE.FILE_SAME_DATA", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tệp tin không hợp lệ, hãy Browse đến t tin hợp lệ!.
    '''</summary>
    Friend Shared ReadOnly Property frmSearchCMP2FILE_FILENAME_MUST_VALID() As String
        Get
            Return ResourceManager.GetString("frmSearchCMP2FILE.FILENAME_MUST_VALID", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Bạn phải chọn file trước khi muốn nạp dữ liệu !.
    '''</summary>
    Friend Shared ReadOnly Property frmSearchCMP2FILE_FilePathEmpty() As String
        Get
            Return ResourceManager.GetString("frmSearchCMP2FILE.FilePathEmpty", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tải dữ liệu vào cơ sở dữ liệu thành công!.
    '''</summary>
    Friend Shared ReadOnly Property frmSearchCMP2FILE_ImportToDBSuccess() As String
        Get
            Return ResourceManager.GetString("frmSearchCMP2FILE.ImportToDBSuccess", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Dữ liệu trên file bị trùng khóa!.
    '''</summary>
    Friend Shared ReadOnly Property frmSearchCMP2FILE_NewdataInvalidKey() As String
        Get
            Return ResourceManager.GetString("frmSearchCMP2FILE.NewdataInvalidKey", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Không có dữ liệu!.
    '''</summary>
    Friend Shared ReadOnly Property frmSearchCMP2FILE_NothingToExport() As String
        Get
            Return ResourceManager.GetString("frmSearchCMP2FILE.NothingToExport", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Dữ liệu trên hệ thống bị trùng khóa!.
    '''</summary>
    Friend Shared ReadOnly Property frmSearchCMP2FILE_OlddataInvalidKey() As String
        Get
            Return ResourceManager.GetString("frmSearchCMP2FILE.OlddataInvalidKey", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Nút chọn:.
    '''</summary>
    Friend Shared ReadOnly Property grbButton() As String
        Get
            Return ResourceManager.GetString("grbButton", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Từ file:.
    '''</summary>
    Friend Shared ReadOnly Property grbFiles() As String
        Get
            Return ResourceManager.GetString("grbFiles", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tới file:.
    '''</summary>
    Friend Shared ReadOnly Property grbFromFile() As String
        Get
            Return ResourceManager.GetString("grbFromFile", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Kết quả đối chiếu:.
    '''</summary>
    Friend Shared ReadOnly Property grbSearchResult() As String
        Get
            Return ResourceManager.GetString("grbSearchResult", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Nguồn:.
    '''</summary>
    Friend Shared ReadOnly Property grbSources() As String
        Get
            Return ResourceManager.GetString("grbSources", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Phân loại: 1.Không có trên file dữ liệu, 2.Không có trong hệ thống, 3. Có trên cả hai nhưng dữ liệu #.
    '''</summary>
    Friend Shared ReadOnly Property grid_Footer() As String
        Get
            Return ResourceManager.GetString("grid.Footer", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Khóa so sánh.
    '''</summary>
    Friend Shared ReadOnly Property grid_KEY() As String
        Get
            Return ResourceManager.GetString("grid.KEY", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Giá trị trên file.
    '''</summary>
    Friend Shared ReadOnly Property grid_NEWVALUE() As String
        Get
            Return ResourceManager.GetString("grid.NEWVALUE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Giá trị hệ thống.
    '''</summary>
    Friend Shared ReadOnly Property grid_OLDVALUE() As String
        Get
            Return ResourceManager.GetString("grid.OLDVALUE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Phân loại.
    '''</summary>
    Friend Shared ReadOnly Property grid_TYPE() As String
        Get
            Return ResourceManager.GetString("grid.TYPE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Giá trị.
    '''</summary>
    Friend Shared ReadOnly Property grid_VALUE() As String
        Get
            Return ResourceManager.GetString("grid.VALUE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tổng số bản ghi:.
    '''</summary>
    Friend Shared ReadOnly Property GridEx_FooterRow() As String
        Get
            Return ResourceManager.GetString("GridEx.FooterRow", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Hãy kéo cột cần nhóm vào đây!.
    '''</summary>
    Friend Shared ReadOnly Property GridEx_GroupByRow() As String
        Get
            Return ResourceManager.GetString("GridEx.GroupByRow", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Đối chiếu giữ liệu từ file.
    '''</summary>
    Friend Shared ReadOnly Property lblCaption() As String
        Get
            Return ResourceManager.GetString("lblCaption", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Loại file:.
    '''</summary>
    Friend Shared ReadOnly Property lblFileType() As String
        Get
            Return ResourceManager.GetString("lblFileType", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tên file:.
    '''</summary>
    Friend Shared ReadOnly Property lblFromFile() As String
        Get
            Return ResourceManager.GetString("lblFromFile", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Địa chỉ máy chủ:.
    '''</summary>
    Friend Shared ReadOnly Property lblServerAddress() As String
        Get
            Return ResourceManager.GetString("lblServerAddress", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tên file:.
    '''</summary>
    Friend Shared ReadOnly Property lblSrcFileName() As String
        Get
            Return ResourceManager.GetString("lblSrcFileName", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Trung tâm giao dịch:.
    '''</summary>
    Friend Shared ReadOnly Property lblTradingCenter() As String
        Get
            Return ResourceManager.GetString("lblTradingCenter", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Ngày đối chiếu:.
    '''</summary>
    Friend Shared ReadOnly Property lblTXDATE() As String
        Get
            Return ResourceManager.GetString("lblTXDATE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Không tìm thấy dữ liệu từ máy chủ giá.
    '''</summary>
    Friend Shared ReadOnly Property NO_DATA_FOUND() As String
        Get
            Return ResourceManager.GetString("NO_DATA_FOUND", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to order by `MÃ CK(4)`,`SỐ TK(10)`,`GIÁ (VNĐ)(13)`,`SỐ LƯỢNG(14)`,`GIÁ TRỊ (VNĐ)(15)`,`SỐ LƯỢNG(16)`,`GIÁ TRỊ (VNĐ)(17)`.
    '''</summary>
    Friend Shared ReadOnly Property ODCMPVSDORDERBY() As String
        Get
            Return ResourceManager.GetString("ODCMPVSDORDERBY", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Bạn có chắc muốn nhận kết quả giao dịch từ file @?.
    '''</summary>
    Friend Shared ReadOnly Property READ_CONFIRMATION() As String
        Get
            Return ResourceManager.GetString("READ_CONFIRMATION", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Nhận dữ liệu thành công..
    '''</summary>
    Friend Shared ReadOnly Property READ_DATA_SUCCESSFULLY() As String
        Get
            Return ResourceManager.GetString("READ_DATA_SUCCESSFULLY", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Nhận dữ liệu từ file @ thành công!.
    '''</summary>
    Friend Shared ReadOnly Property READ_FILE_SUCCESSFULLY() As String
        Get
            Return ResourceManager.GetString("READ_FILE_SUCCESSFULLY", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Bạn có muốn lưu kết quả giao dịch?.
    '''</summary>
    Friend Shared ReadOnly Property SAVE_CONFIRMATION() As String
        Get
            Return ResourceManager.GetString("SAVE_CONFIRMATION", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Lưu thông tin thành công!.
    '''</summary>
    Friend Shared ReadOnly Property SAVED_STATUS() As String
        Get
            Return ResourceManager.GetString("SAVED_STATUS", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Lưu tới dòng @... Xin vui lòng đợi!.
    '''</summary>
    Friend Shared ReadOnly Property SAVING_STATUS() As String
        Get
            Return ResourceManager.GetString("SAVING_STATUS", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to \\192.168.100.203.
    '''</summary>
    Friend Shared ReadOnly Property txtServerAddress() As String
        Get
            Return ResourceManager.GetString("txtServerAddress", resourceCulture)
        End Get
    End Property
End Class
