'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class frmSearchCMP2FILE_EN
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("AppCore.frmSearchCMP2FILE-EN", GetType(frmSearchCMP2FILE_EN).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to ....
    '''</summary>
    Friend Shared ReadOnly Property btnBrowser() As String
        Get
            Return ResourceManager.GetString("btnBrowser", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Cancel.
    '''</summary>
    Friend Shared ReadOnly Property btnCancel() As String
        Get
            Return ResourceManager.GetString("btnCancel", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Compare.
    '''</summary>
    Friend Shared ReadOnly Property btnCompare() As String
        Get
            Return ResourceManager.GetString("btnCompare", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Export.
    '''</summary>
    Friend Shared ReadOnly Property btnExport() As String
        Get
            Return ResourceManager.GetString("btnExport", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Choose VSD File.
    '''</summary>
    Friend Shared ReadOnly Property btnFileCSV() As String
        Get
            Return ResourceManager.GetString("btnFileCSV", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to ....
    '''</summary>
    Friend Shared ReadOnly Property btnOpenFile() As String
        Get
            Return ResourceManager.GetString("btnOpenFile", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Compare data!.
    '''</summary>
    Friend Shared ReadOnly Property frmSearchCMP2FILE() As String
        Get
            Return ResourceManager.GetString("frmSearchCMP2FILE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Has an error when transport data !.
    '''</summary>
    Friend Shared ReadOnly Property frmSearchCMP2FILE_CannotImportToDB() As String
        Get
            Return ResourceManager.GetString("frmSearchCMP2FILE.CannotImportToDB", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Cannot open data file.Please setting again !.
    '''</summary>
    Friend Shared ReadOnly Property frmSearchCMP2FILE_CannotOpenFile() As String
        Get
            Return ResourceManager.GetString("frmSearchCMP2FILE.CannotOpenFile", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Export Successfull.
    '''</summary>
    Friend Shared ReadOnly Property frmSearchCMP2FILE_ExportSuccessful() As String
        Get
            Return ResourceManager.GetString("frmSearchCMP2FILE.ExportSuccessful", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Same data!.
    '''</summary>
    Friend Shared ReadOnly Property frmSearchCMP2FILE_FILE_SAME_DATA() As String
        Get
            Return ResourceManager.GetString("frmSearchCMP2FILE.FILE_SAME_DATA", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to File name is invalid. Please re-type file name or click &lt;Browse&gt; button and choose the file..
    '''</summary>
    Friend Shared ReadOnly Property frmSearchCMP2FILE_FILENAME_MUST_VALID() As String
        Get
            Return ResourceManager.GetString("frmSearchCMP2FILE.FILENAME_MUST_VALID", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to You should choose file before load data!.
    '''</summary>
    Friend Shared ReadOnly Property frmSearchCMP2FILE_FilePathEmpty() As String
        Get
            Return ResourceManager.GetString("frmSearchCMP2FILE.FilePathEmpty", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Data transport to DB successful !.
    '''</summary>
    Friend Shared ReadOnly Property frmSearchCMP2FILE_ImportToDBSuccess() As String
        Get
            Return ResourceManager.GetString("frmSearchCMP2FILE.ImportToDBSuccess", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Data in file invalid key!.
    '''</summary>
    Friend Shared ReadOnly Property frmSearchCMP2FILE_NewdataInvalidKey() As String
        Get
            Return ResourceManager.GetString("frmSearchCMP2FILE.NewdataInvalidKey", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to No data to export!.
    '''</summary>
    Friend Shared ReadOnly Property frmSearchCMP2FILE_NothingToExport() As String
        Get
            Return ResourceManager.GetString("frmSearchCMP2FILE.NothingToExport", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Data in system invalid key!.
    '''</summary>
    Friend Shared ReadOnly Property frmSearchCMP2FILE_OlddataInvalidKey() As String
        Get
            Return ResourceManager.GetString("frmSearchCMP2FILE.OlddataInvalidKey", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Select button :.
    '''</summary>
    Friend Shared ReadOnly Property grbButton() As String
        Get
            Return ResourceManager.GetString("grbButton", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to From files:.
    '''</summary>
    Friend Shared ReadOnly Property grbFiles() As String
        Get
            Return ResourceManager.GetString("grbFiles", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to From files:.
    '''</summary>
    Friend Shared ReadOnly Property grbFromFile() As String
        Get
            Return ResourceManager.GetString("grbFromFile", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Search result :.
    '''</summary>
    Friend Shared ReadOnly Property grbSearchResult() As String
        Get
            Return ResourceManager.GetString("grbSearchResult", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Sources:.
    '''</summary>
    Friend Shared ReadOnly Property grbSources() As String
        Get
            Return ResourceManager.GetString("grbSources", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Type: 1. No in file, 2. Not in system data, 3. Different.
    '''</summary>
    Friend Shared ReadOnly Property grid_Footer() As String
        Get
            Return ResourceManager.GetString("grid.Footer", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Keys compare.
    '''</summary>
    Friend Shared ReadOnly Property grid_KEY() As String
        Get
            Return ResourceManager.GetString("grid.KEY", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Values in file.
    '''</summary>
    Friend Shared ReadOnly Property grid_NEWVALUE() As String
        Get
            Return ResourceManager.GetString("grid.NEWVALUE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Values in system.
    '''</summary>
    Friend Shared ReadOnly Property grid_OLDVALUE() As String
        Get
            Return ResourceManager.GetString("grid.OLDVALUE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Type.
    '''</summary>
    Friend Shared ReadOnly Property grid_TYPE() As String
        Get
            Return ResourceManager.GetString("grid.TYPE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Values compare.
    '''</summary>
    Friend Shared ReadOnly Property grid_VALUE() As String
        Get
            Return ResourceManager.GetString("grid.VALUE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Sum of records: .
    '''</summary>
    Friend Shared ReadOnly Property GridEx_FooterRow() As String
        Get
            Return ResourceManager.GetString("GridEx.FooterRow", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Drag and drop column which should be grouped!.
    '''</summary>
    Friend Shared ReadOnly Property GridEx_GroupByRow() As String
        Get
            Return ResourceManager.GetString("GridEx.GroupByRow", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Compare data from file.
    '''</summary>
    Friend Shared ReadOnly Property lblCaption() As String
        Get
            Return ResourceManager.GetString("lblCaption", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to File type:.
    '''</summary>
    Friend Shared ReadOnly Property lblFileType() As String
        Get
            Return ResourceManager.GetString("lblFileType", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to File name:.
    '''</summary>
    Friend Shared ReadOnly Property lblFromFile() As String
        Get
            Return ResourceManager.GetString("lblFromFile", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Server address :.
    '''</summary>
    Friend Shared ReadOnly Property lblServerAddress() As String
        Get
            Return ResourceManager.GetString("lblServerAddress", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to File name :.
    '''</summary>
    Friend Shared ReadOnly Property lblSrcFileName() As String
        Get
            Return ResourceManager.GetString("lblSrcFileName", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Trading center:.
    '''</summary>
    Friend Shared ReadOnly Property lblTradingCenter() As String
        Get
            Return ResourceManager.GetString("lblTradingCenter", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Compare date:.
    '''</summary>
    Friend Shared ReadOnly Property lblTXDATE() As String
        Get
            Return ResourceManager.GetString("lblTXDATE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to No data found from quote !.
    '''</summary>
    Friend Shared ReadOnly Property NO_DATA_FOUND() As String
        Get
            Return ResourceManager.GetString("NO_DATA_FOUND", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to order by `MÃ CK(4)`,`SỐ TK(10)`,`GIÁ (VNĐ)(13)`,`SỐ LƯỢNG(14)`,`GIÁ TRỊ (VNĐ)(15)`,`SỐ LƯỢNG(16)`,`GIÁ TRỊ (VNĐ)(17)`.
    '''</summary>
    Friend Shared ReadOnly Property ODCMPVSDORDERBY() As String
        Get
            Return ResourceManager.GetString("ODCMPVSDORDERBY", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Are you sure to read securities information from file @?.
    '''</summary>
    Friend Shared ReadOnly Property READ_CONFIRMATION() As String
        Get
            Return ResourceManager.GetString("READ_CONFIRMATION", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Read data successfully !.
    '''</summary>
    Friend Shared ReadOnly Property READ_DATA_SUCCESSFULLY() As String
        Get
            Return ResourceManager.GetString("READ_DATA_SUCCESSFULLY", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Read securities information from file @ successfully!.
    '''</summary>
    Friend Shared ReadOnly Property READ_FILE_SUCCESSFULLY() As String
        Get
            Return ResourceManager.GetString("READ_FILE_SUCCESSFULLY", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Are you sure to save trading result information?.
    '''</summary>
    Friend Shared ReadOnly Property SAVE_CONFIRMATION() As String
        Get
            Return ResourceManager.GetString("SAVE_CONFIRMATION", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Saving securities information is completed!.
    '''</summary>
    Friend Shared ReadOnly Property SAVED_STATUS() As String
        Get
            Return ResourceManager.GetString("SAVED_STATUS", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Saving on row @... Please wait!.
    '''</summary>
    Friend Shared ReadOnly Property SAVING_STATUS() As String
        Get
            Return ResourceManager.GetString("SAVING_STATUS", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to \\192.168.100.203.
    '''</summary>
    Friend Shared ReadOnly Property txtServerAddress() As String
        Get
            Return ResourceManager.GetString("txtServerAddress", resourceCulture)
        End Get
    End Property
End Class
