'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class frmTransact_EN
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("AppCore.frmTransact-EN", GetType(frmTransact_EN).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Account.
    '''</summary>
    Friend Shared ReadOnly Property ACCOUNT_EN() As String
        Get
            Return ResourceManager.GetString("ACCOUNT_EN", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Account entries.
    '''</summary>
    Friend Shared ReadOnly Property ACCOUNTENTRY_EN() As String
        Get
            Return ResourceManager.GetString("ACCOUNTENTRY_EN", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Amount.
    '''</summary>
    Friend Shared ReadOnly Property AMOUNT_EN() As String
        Get
            Return ResourceManager.GetString("AMOUNT_EN", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Posting date should before current date!.
    '''</summary>
    Friend Shared ReadOnly Property BUSDATE_AFTER_CURRDATE() As String
        Get
            Return ResourceManager.GetString("BUSDATE_AFTER_CURRDATE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Posting date is not valid!.
    '''</summary>
    Friend Shared ReadOnly Property BUSDATE_NOT_VALID() As String
        Get
            Return ResourceManager.GetString("BUSDATE_NOT_VALID", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Giao dịch này là giao dịch của hệ thống chạy cuối ngày nên không thể thực thi từ màn hình !.
    '''</summary>
    Friend Shared ReadOnly Property CANNOTEXCUTETRANSACT() As String
        Get
            Return ResourceManager.GetString("CANNOTEXCUTETRANSACT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Currency.
    '''</summary>
    Friend Shared ReadOnly Property CCYCD_EN() As String
        Get
            Return ResourceManager.GetString("CCYCD_EN", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Credit.
    '''</summary>
    Friend Shared ReadOnly Property CRAMT_EN() As String
        Get
            Return ResourceManager.GetString("CRAMT_EN", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Debit/Credit.
    '''</summary>
    Friend Shared ReadOnly Property DORC_EN() As String
        Get
            Return ResourceManager.GetString("DORC_EN", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Debit.
    '''</summary>
    Friend Shared ReadOnly Property DRAMT_EN() As String
        Get
            Return ResourceManager.GetString("DRAMT_EN", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Margin type does not permit of this transaction..
    '''</summary>
    Friend Shared ReadOnly Property ERR_CF_AFMAST_MRSTYPE_INVALID() As String
        Get
            Return ResourceManager.GetString("ERR_CF_AFMAST_MRSTYPE_INVALID", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Length of custody code is invalid.
    '''</summary>
    Friend Shared ReadOnly Property ERR_CUSTODYCD_INVALID_LENGTH() As String
        Get
            Return ResourceManager.GetString("ERR_CUSTODYCD_INVALID_LENGTH", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Invalid custody code format.
    '''</summary>
    Friend Shared ReadOnly Property ERR_CUSTODYCD_INVALID_PCFLAG_PC() As String
        Get
            Return ResourceManager.GetString("ERR_CUSTODYCD_INVALID_PCFLAG_PC", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Data not found.
    '''</summary>
    Friend Shared ReadOnly Property ERR_DATA_NOTFOUND() As String
        Get
            Return ResourceManager.GetString("ERR_DATA_NOTFOUND", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Invalid date value!.
    '''</summary>
    Friend Shared ReadOnly Property ERR_DATE_VALUE() As String
        Get
            Return ResourceManager.GetString("ERR_DATE_VALUE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Invalid numeric value for numeric required field!.
    '''</summary>
    Friend Shared ReadOnly Property ERR_INVALID_NUMERIC_NUMBER() As String
        Get
            Return ResourceManager.GetString("ERR_INVALID_NUMERIC_NUMBER", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to ERR_INVALID_POSTING_DATE.
    '''</summary>
    Friend Shared ReadOnly Property ERR_INVALID_POSTING_DATE() As String
        Get
            Return ResourceManager.GetString("ERR_INVALID_POSTING_DATE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Invalid input value!.
    '''</summary>
    Friend Shared ReadOnly Property ERR_LOOKUP_VALUE() As String
        Get
            Return ResourceManager.GetString("ERR_LOOKUP_VALUE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Field {FIELDNAME} : Invalid Input value.
    '''</summary>
    Friend Shared ReadOnly Property ERR_NULL_COMBO() As String
        Get
            Return ResourceManager.GetString("ERR_NULL_COMBO", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Not enough information to do the transaction!.
    '''</summary>
    Friend Shared ReadOnly Property ERR_NULL_COMBOEX() As String
        Get
            Return ResourceManager.GetString("ERR_NULL_COMBOEX", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to This mandatory field can not be null!.
    '''</summary>
    Friend Shared ReadOnly Property ERR_NULL_VALUE() As String
        Get
            Return ResourceManager.GetString("ERR_NULL_VALUE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Invalid numerical value!.
    '''</summary>
    Friend Shared ReadOnly Property ERR_NUMERIC_VALUE() As String
        Get
            Return ResourceManager.GetString("ERR_NUMERIC_VALUE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Over length for  numerical value, length should be smaller tham 20 characters!.
    '''</summary>
    Friend Shared ReadOnly Property ERR_OVER_DBL_VALUE() As String
        Get
            Return ResourceManager.GetString("ERR_OVER_DBL_VALUE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Posting date must be work date!.
    '''</summary>
    Friend Shared ReadOnly Property ERR_POSTING_DATE_MUST_BE_WORK_DATE() As String
        Get
            Return ResourceManager.GetString("ERR_POSTING_DATE_MUST_BE_WORK_DATE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Transaction code not found.
    '''</summary>
    Friend Shared ReadOnly Property ERR_TLTXCD_NOTFOUND() As String
        Get
            Return ResourceManager.GetString("ERR_TLTXCD_NOTFOUND", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Fee amount.
    '''</summary>
    Friend Shared ReadOnly Property FEEAMT_EN() As String
        Get
            Return ResourceManager.GetString("FEEAMT_EN", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Fee code.
    '''</summary>
    Friend Shared ReadOnly Property FEECD_EN() As String
        Get
            Return ResourceManager.GetString("FEECD_EN", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Fee details.
    '''</summary>
    Friend Shared ReadOnly Property FEEDETAIL_EN() As String
        Get
            Return ResourceManager.GetString("FEEDETAIL_EN", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Fee name.
    '''</summary>
    Friend Shared ReadOnly Property FEENAME_EN() As String
        Get
            Return ResourceManager.GetString("FEENAME_EN", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Fee rate.
    '''</summary>
    Friend Shared ReadOnly Property FEERATE_EN() As String
        Get
            Return ResourceManager.GetString("FEERATE_EN", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to File voucher template not exists!.
    '''</summary>
    Friend Shared ReadOnly Property FileNotExists() As String
        Get
            Return ResourceManager.GetString("FileNotExists", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Fee type.
    '''</summary>
    Friend Shared ReadOnly Property FORP_EN() As String
        Get
            Return ResourceManager.GetString("FORP_EN", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Enter transaction.
    '''</summary>
    Friend Shared ReadOnly Property frmTransact() As String
        Get
            Return ResourceManager.GetString("frmTransact", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Approve Successful!.
    '''</summary>
    Friend Shared ReadOnly Property frmTransact_ApproveSuccessful() As String
        Get
            Return ResourceManager.GetString("frmTransact.ApproveSuccessful", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to A&amp;djust.
    '''</summary>
    Friend Shared ReadOnly Property frmTransact_btnAdjust() As String
        Get
            Return ResourceManager.GetString("frmTransact.btnAdjust", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Approve.
    '''</summary>
    Friend Shared ReadOnly Property frmTransact_btnApprove() As String
        Get
            Return ResourceManager.GetString("frmTransact.btnApprove", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Cancel.
    '''</summary>
    Friend Shared ReadOnly Property frmTransact_btnCANCEL() As String
        Get
            Return ResourceManager.GetString("frmTransact.btnCANCEL", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Postmap.
    '''</summary>
    Friend Shared ReadOnly Property frmTransact_btnEntries() As String
        Get
            Return ResourceManager.GetString("frmTransact.btnEntries", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;OK.
    '''</summary>
    Friend Shared ReadOnly Property frmTransact_btnOK() As String
        Get
            Return ResourceManager.GetString("frmTransact.btnOK", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Re&amp;fuse.
    '''</summary>
    Friend Shared ReadOnly Property frmTransact_btnRefuse() As String
        Get
            Return ResourceManager.GetString("frmTransact.btnRefuse", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Reject.
    '''</summary>
    Friend Shared ReadOnly Property frmTransact_btnReject() As String
        Get
            Return ResourceManager.GetString("frmTransact.btnReject", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Print &amp;Voucher.
    '''</summary>
    Friend Shared ReadOnly Property frmTransact_btnVoucher() As String
        Get
            Return ResourceManager.GetString("frmTransact.btnVoucher", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to This is the last pending transaction!.
    '''</summary>
    Friend Shared ReadOnly Property frmTransact_CanNotShowNext() As String
        Get
            Return ResourceManager.GetString("frmTransact.CanNotShowNext", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Delete Successful!.
    '''</summary>
    Friend Shared ReadOnly Property frmTransact_DeleteSuccessful() As String
        Get
            Return ResourceManager.GetString("frmTransact.DeleteSuccessful", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Transaction screen.
    '''</summary>
    Friend Shared ReadOnly Property frmTransact_lblCaption() As String
        Get
            Return ResourceManager.GetString("frmTransact.lblCaption", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Transaction code:.
    '''</summary>
    Friend Shared ReadOnly Property frmTransact_lblTransCode() As String
        Get
            Return ResourceManager.GetString("frmTransact.lblTransCode", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Post Map, VAT voucher should not be all empty!.
    '''</summary>
    Friend Shared ReadOnly Property frmTransact_PostMapEmpty() As String
        Get
            Return ResourceManager.GetString("frmTransact.PostMapEmpty", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Refuse successful.
    '''</summary>
    Friend Shared ReadOnly Property frmTransact_RefuseMessage() As String
        Get
            Return ResourceManager.GetString("frmTransact.RefuseMessage", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Please enter your comment!.
    '''</summary>
    Friend Shared ReadOnly Property frmTransact_RejectComment() As String
        Get
            Return ResourceManager.GetString("frmTransact.RejectComment", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Reject successful!.
    '''</summary>
    Friend Shared ReadOnly Property frmTransact_RejectedSuccessful() As String
        Get
            Return ResourceManager.GetString("frmTransact.RejectedSuccessful", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Fee Account.
    '''</summary>
    Friend Shared ReadOnly Property GLACCTNO_EN() As String
        Get
            Return ResourceManager.GetString("GLACCTNO_EN", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Trans code:.
    '''</summary>
    Friend Shared ReadOnly Property lblTransCode() As String
        Get
            Return ResourceManager.GetString("lblTransCode", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Max amount.
    '''</summary>
    Friend Shared ReadOnly Property MAXVAL_EN() As String
        Get
            Return ResourceManager.GetString("MAXVAL_EN", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Min amount.
    '''</summary>
    Friend Shared ReadOnly Property MINVAL_EN() As String
        Get
            Return ResourceManager.GetString("MINVAL_EN", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Posting date.
    '''</summary>
    Friend Shared ReadOnly Property POSTING_DATE_CAPTION() As String
        Get
            Return ResourceManager.GetString("POSTING_DATE_CAPTION", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Are you sure to print voucher.
    '''</summary>
    Friend Shared ReadOnly Property PrintConfirm() As String
        Get
            Return ResourceManager.GetString("PrintConfirm", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Press F9 for more account/ authorize account infomation.
    '''</summary>
    Friend Shared ReadOnly Property STATUSBAR_ACCINFO() As String
        Get
            Return ResourceManager.GetString("STATUSBAR_ACCINFO", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to No.
    '''</summary>
    Friend Shared ReadOnly Property SUBTXNO_EN() As String
        Get
            Return ResourceManager.GetString("SUBTXNO_EN", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Account Entry.
    '''</summary>
    Friend Shared ReadOnly Property tabAccountEntry() As String
        Get
            Return ResourceManager.GetString("tabAccountEntry", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Fixed Assest.
    '''</summary>
    Friend Shared ReadOnly Property tabFixedAssest() As String
        Get
            Return ResourceManager.GetString("tabFixedAssest", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to VAT Voucher.
    '''</summary>
    Friend Shared ReadOnly Property tabVATVoucher() As String
        Get
            Return ResourceManager.GetString("tabVATVoucher", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Date on this client and date on branch are diffirent, please logout and login!.
    '''</summary>
    Friend Shared ReadOnly Property TxDateBusDate() As String
        Get
            Return ResourceManager.GetString("TxDateBusDate", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Transact num is empty! .
    '''</summary>
    Friend Shared ReadOnly Property TXNUM_EMPTY() As String
        Get
            Return ResourceManager.GetString("TXNUM_EMPTY", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to VAT rate.
    '''</summary>
    Friend Shared ReadOnly Property VATRATE_EN() As String
        Get
            Return ResourceManager.GetString("VATRATE_EN", resourceCulture)
        End Get
    End Property
End Class
