'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class frmTransact_VN
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("AppCore.frmTransact-VN", GetType(frmTransact_VN).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tài khoản.
    '''</summary>
    Friend Shared ReadOnly Property ACCOUNT_EN() As String
        Get
            Return ResourceManager.GetString("ACCOUNT_EN", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Hạch toán.
    '''</summary>
    Friend Shared ReadOnly Property ACCOUNTENTRY_EN() As String
        Get
            Return ResourceManager.GetString("ACCOUNTENTRY_EN", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Số tiền.
    '''</summary>
    Friend Shared ReadOnly Property AMOUNT_EN() As String
        Get
            Return ResourceManager.GetString("AMOUNT_EN", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Ngày chứng từ không thể lớn hơn ngày hiện tại!.
    '''</summary>
    Friend Shared ReadOnly Property BUSDATE_AFTER_CURRDATE() As String
        Get
            Return ResourceManager.GetString("BUSDATE_AFTER_CURRDATE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Ngày chứng từ không hợp lệ!.
    '''</summary>
    Friend Shared ReadOnly Property BUSDATE_NOT_VALID() As String
        Get
            Return ResourceManager.GetString("BUSDATE_NOT_VALID", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Giao dịch này là giao dịch của hệ thống chạy cuối ngày nên không thể thực thi từ màn hình !.
    '''</summary>
    Friend Shared ReadOnly Property CANNOTEXCUTETRANSACT() As String
        Get
            Return ResourceManager.GetString("CANNOTEXCUTETRANSACT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Loại tiền.
    '''</summary>
    Friend Shared ReadOnly Property CCYCD_EN() As String
        Get
            Return ResourceManager.GetString("CCYCD_EN", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Có.
    '''</summary>
    Friend Shared ReadOnly Property CRAMT_EN() As String
        Get
            Return ResourceManager.GetString("CRAMT_EN", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Nợ/Có.
    '''</summary>
    Friend Shared ReadOnly Property DORC_EN() As String
        Get
            Return ResourceManager.GetString("DORC_EN", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Nợ.
    '''</summary>
    Friend Shared ReadOnly Property DRAMT_EN() As String
        Get
            Return ResourceManager.GetString("DRAMT_EN", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Loại hình Margin không thể thực hiện giao dịch này..
    '''</summary>
    Friend Shared ReadOnly Property ERR_CF_AFMAST_MRSTYPE_INVALID() As String
        Get
            Return ResourceManager.GetString("ERR_CF_AFMAST_MRSTYPE_INVALID", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Độ dài số tài khoản lưu ký không hợp lệ.
    '''</summary>
    Friend Shared ReadOnly Property ERR_CUSTODYCD_INVALID_LENGTH() As String
        Get
            Return ResourceManager.GetString("ERR_CUSTODYCD_INVALID_LENGTH", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Khuôn dạng số tài khoản lưu ký không hợp lệ.
    '''</summary>
    Friend Shared ReadOnly Property ERR_CUSTODYCD_INVALID_PCFLAG_PC() As String
        Get
            Return ResourceManager.GetString("ERR_CUSTODYCD_INVALID_PCFLAG_PC", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Không tìm thấy dữ liệu nhập vào.
    '''</summary>
    Friend Shared ReadOnly Property ERR_DATA_NOTFOUND() As String
        Get
            Return ResourceManager.GetString("ERR_DATA_NOTFOUND", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Giá trị ngày tháng không hợp lệ.
    '''</summary>
    Friend Shared ReadOnly Property ERR_DATE_VALUE() As String
        Get
            Return ResourceManager.GetString("ERR_DATE_VALUE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Giá trị truờng số không hợp lệ!.
    '''</summary>
    Friend Shared ReadOnly Property ERR_INVALID_NUMERIC_NUMBER() As String
        Get
            Return ResourceManager.GetString("ERR_INVALID_NUMERIC_NUMBER", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Ngày thực hiện giao dịch không hợp lệ!.
    '''</summary>
    Friend Shared ReadOnly Property ERR_INVALID_POSTING_DATE() As String
        Get
            Return ResourceManager.GetString("ERR_INVALID_POSTING_DATE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Giá trị nhập vào không hợp lệ!.
    '''</summary>
    Friend Shared ReadOnly Property ERR_LOOKUP_VALUE() As String
        Get
            Return ResourceManager.GetString("ERR_LOOKUP_VALUE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Trường {FIELDNAME} : Giá trị nhập không hợp lệ.
    '''</summary>
    Friend Shared ReadOnly Property ERR_NULL_COMBO() As String
        Get
            Return ResourceManager.GetString("ERR_NULL_COMBO", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Chưa đủ thông tin để làm giao dịch !.
    '''</summary>
    Friend Shared ReadOnly Property ERR_NULL_COMBOEX() As String
        Get
            Return ResourceManager.GetString("ERR_NULL_COMBOEX", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Trường bắt buộc không thể để trống!.
    '''</summary>
    Friend Shared ReadOnly Property ERR_NULL_VALUE() As String
        Get
            Return ResourceManager.GetString("ERR_NULL_VALUE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Giá trị số không hợp lệ.
    '''</summary>
    Friend Shared ReadOnly Property ERR_NUMERIC_VALUE() As String
        Get
            Return ResourceManager.GetString("ERR_NUMERIC_VALUE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Giá trị trường số quá dài so với quy định của kiểu số.
    '''</summary>
    Friend Shared ReadOnly Property ERR_OVER_DBL_VALUE() As String
        Get
            Return ResourceManager.GetString("ERR_OVER_DBL_VALUE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Ngày chứng từ phải là ngày làm việc!.
    '''</summary>
    Friend Shared ReadOnly Property ERR_POSTING_DATE_MUST_BE_WORK_DATE() As String
        Get
            Return ResourceManager.GetString("ERR_POSTING_DATE_MUST_BE_WORK_DATE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Không tìm thấy mã giao dịch.
    '''</summary>
    Friend Shared ReadOnly Property ERR_TLTXCD_NOTFOUND() As String
        Get
            Return ResourceManager.GetString("ERR_TLTXCD_NOTFOUND", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Giá trị phí.
    '''</summary>
    Friend Shared ReadOnly Property FEEAMT_EN() As String
        Get
            Return ResourceManager.GetString("FEEAMT_EN", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Mã phí.
    '''</summary>
    Friend Shared ReadOnly Property FEECD_EN() As String
        Get
            Return ResourceManager.GetString("FEECD_EN", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Chi tiết phí.
    '''</summary>
    Friend Shared ReadOnly Property FEEDETAIL_EN() As String
        Get
            Return ResourceManager.GetString("FEEDETAIL_EN", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tên phí.
    '''</summary>
    Friend Shared ReadOnly Property FEENAME_EN() As String
        Get
            Return ResourceManager.GetString("FEENAME_EN", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tỷ lệ phí.
    '''</summary>
    Friend Shared ReadOnly Property FEERATE_EN() As String
        Get
            Return ResourceManager.GetString("FEERATE_EN", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to File mẫu chứng từ không tồn tại!.
    '''</summary>
    Friend Shared ReadOnly Property FileNotExists() As String
        Get
            Return ResourceManager.GetString("FileNotExists", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Loại phí.
    '''</summary>
    Friend Shared ReadOnly Property FORP_EN() As String
        Get
            Return ResourceManager.GetString("FORP_EN", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Nhập giao dịch.
    '''</summary>
    Friend Shared ReadOnly Property frmTransact() As String
        Get
            Return ResourceManager.GetString("frmTransact", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Duyệt giao dịch thành công!.
    '''</summary>
    Friend Shared ReadOnly Property frmTransact_ApproveSuccessful() As String
        Get
            Return ResourceManager.GetString("frmTransact.ApproveSuccessful", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Hiệu chỉnh.
    '''</summary>
    Friend Shared ReadOnly Property frmTransact_btnAdjust() As String
        Get
            Return ResourceManager.GetString("frmTransact.btnAdjust", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Duyệt.
    '''</summary>
    Friend Shared ReadOnly Property frmTransact_btnApprove() As String
        Get
            Return ResourceManager.GetString("frmTransact.btnApprove", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Thoát.
    '''</summary>
    Friend Shared ReadOnly Property frmTransact_btnCANCEL() As String
        Get
            Return ResourceManager.GetString("frmTransact.btnCANCEL", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Hạch toán.
    '''</summary>
    Friend Shared ReadOnly Property frmTransact_btnEntries() As String
        Get
            Return ResourceManager.GetString("frmTransact.btnEntries", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Chấp nhận.
    '''</summary>
    Friend Shared ReadOnly Property frmTransact_btnOK() As String
        Get
            Return ResourceManager.GetString("frmTransact.btnOK", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Hủy &amp;bỏ.
    '''</summary>
    Friend Shared ReadOnly Property frmTransact_btnRefuse() As String
        Get
            Return ResourceManager.GetString("frmTransact.btnRefuse", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Từ &amp;chối.
    '''</summary>
    Friend Shared ReadOnly Property frmTransact_btnReject() As String
        Get
            Return ResourceManager.GetString("frmTransact.btnReject", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;In chứng từ.
    '''</summary>
    Friend Shared ReadOnly Property frmTransact_btnVoucher() As String
        Get
            Return ResourceManager.GetString("frmTransact.btnVoucher", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Đây là giao dịch chờ duyệt cuối cùng!.
    '''</summary>
    Friend Shared ReadOnly Property frmTransact_CanNotShowNext() As String
        Get
            Return ResourceManager.GetString("frmTransact.CanNotShowNext", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Xóa giao dịch thành công!.
    '''</summary>
    Friend Shared ReadOnly Property frmTransact_DeleteSuccessful() As String
        Get
            Return ResourceManager.GetString("frmTransact.DeleteSuccessful", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Màn hình giao dịch:.
    '''</summary>
    Friend Shared ReadOnly Property frmTransact_lblCaption() As String
        Get
            Return ResourceManager.GetString("frmTransact.lblCaption", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Mã giao dịch:.
    '''</summary>
    Friend Shared ReadOnly Property frmTransact_lblTransCode() As String
        Get
            Return ResourceManager.GetString("frmTransact.lblTransCode", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Không có bút toán!.
    '''</summary>
    Friend Shared ReadOnly Property frmTransact_PostMapEmpty() As String
        Get
            Return ResourceManager.GetString("frmTransact.PostMapEmpty", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Hủy bỏ giao dịch thành công!.
    '''</summary>
    Friend Shared ReadOnly Property frmTransact_RefuseMessage() As String
        Get
            Return ResourceManager.GetString("frmTransact.RefuseMessage", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Xin vui lòng hãy nhập lý do vì sao từ chối! .
    '''</summary>
    Friend Shared ReadOnly Property frmTransact_RejectComment() As String
        Get
            Return ResourceManager.GetString("frmTransact.RejectComment", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Từ chối thành công!.
    '''</summary>
    Friend Shared ReadOnly Property frmTransact_RejectedSuccessful() As String
        Get
            Return ResourceManager.GetString("frmTransact.RejectedSuccessful", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tài khoản phí.
    '''</summary>
    Friend Shared ReadOnly Property GLACCTNO_EN() As String
        Get
            Return ResourceManager.GetString("GLACCTNO_EN", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Mã giao dịch:.
    '''</summary>
    Friend Shared ReadOnly Property lblTransCode() As String
        Get
            Return ResourceManager.GetString("lblTransCode", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Phí tối đa.
    '''</summary>
    Friend Shared ReadOnly Property MAXVAL_EN() As String
        Get
            Return ResourceManager.GetString("MAXVAL_EN", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Phí tối thiểu.
    '''</summary>
    Friend Shared ReadOnly Property MINVAL_EN() As String
        Get
            Return ResourceManager.GetString("MINVAL_EN", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Ngày chứng từ.
    '''</summary>
    Friend Shared ReadOnly Property POSTING_DATE_CAPTION() As String
        Get
            Return ResourceManager.GetString("POSTING_DATE_CAPTION", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Bạn có thực sự muốn in chứng từ?.
    '''</summary>
    Friend Shared ReadOnly Property PrintConfirm() As String
        Get
            Return ResourceManager.GetString("PrintConfirm", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Bấm F9 tại ô Tiểu khoản để xem chữ ký chủ tài khoản và chi tiết người được ủy quyền.
    '''</summary>
    Friend Shared ReadOnly Property STATUSBAR_ACCINFO() As String
        Get
            Return ResourceManager.GetString("STATUSBAR_ACCINFO", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to STT.
    '''</summary>
    Friend Shared ReadOnly Property SUBTXNO_EN() As String
        Get
            Return ResourceManager.GetString("SUBTXNO_EN", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Bút toán.
    '''</summary>
    Friend Shared ReadOnly Property tabAccountEntry() As String
        Get
            Return ResourceManager.GetString("tabAccountEntry", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to TSCĐ.
    '''</summary>
    Friend Shared ReadOnly Property tabFixedAssest() As String
        Get
            Return ResourceManager.GetString("tabFixedAssest", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to VAT.
    '''</summary>
    Friend Shared ReadOnly Property tabVATVoucher() As String
        Get
            Return ResourceManager.GetString("tabVATVoucher", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Ngày của máy trạm và ngày của máy chủ khác nhau, hãy thoát khỏi chương trình!.
    '''</summary>
    Friend Shared ReadOnly Property TxDateBusDate() As String
        Get
            Return ResourceManager.GetString("TxDateBusDate", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Chưa có mã giao dịch!.
    '''</summary>
    Friend Shared ReadOnly Property TXNUM_EMPTY() As String
        Get
            Return ResourceManager.GetString("TXNUM_EMPTY", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tỷ lệ VAT.
    '''</summary>
    Friend Shared ReadOnly Property VATRATE_EN() As String
        Get
            Return ResourceManager.GetString("VATRATE_EN", resourceCulture)
        End Get
    End Property
End Class
