'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5446
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"), _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()> _
Friend Class frmXtraApprove_VN

    Private Shared resourceMan As Global.System.Resources.ResourceManager

    Private Shared resourceCulture As Global.System.Globalization.CultureInfo

    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")> _
    Friend Sub New()
        MyBase.New()
    End Sub

    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager(gc_RootNamespace & "." & "frmApprove-EN", GetType(frmXtraApprove_VN).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property

    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set(value As Global.System.Globalization.CultureInfo)
            resourceCulture = Value
        End Set
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Error when approving!.
    '''</summary>
    Friend Shared ReadOnly Property ApprovalFailed() As String
        Get
            Return ResourceManager.GetString("ApprovalFailed", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Data is successfully approved.
    '''</summary>
    Friend Shared ReadOnly Property ApproveSuccessful() As String
        Get
            Return ResourceManager.GetString("ApproveSuccessful", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Branch code in VND account number doesn&apos;t match with the one in gold account number!.
    '''</summary>
    Friend Shared ReadOnly Property BranchCodeErr() As String
        Get
            Return ResourceManager.GetString("BranchCodeErr", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Approve.
    '''</summary>
    Friend Shared ReadOnly Property btnApprove() As String
        Get
            Return ResourceManager.GetString("btnApprove", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Exit.
    '''</summary>
    Friend Shared ReadOnly Property btnCancel() As String
        Get
            Return ResourceManager.GetString("btnCancel", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Reject.
    '''</summary>
    Friend Shared ReadOnly Property btnReject() As String
        Get
            Return ResourceManager.GetString("btnReject", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Modification History.
    '''</summary>
    Friend Shared ReadOnly Property Caption() As String
        Get
            Return ResourceManager.GetString("Caption", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Reject Denied! No changes have been made..
    '''</summary>
    Friend Shared ReadOnly Property Duyệt_không_thành_công__Không_có_thay_đổi_gì_trên_dữ_liệu_này_() As String
        Get
            Return ResourceManager.GetString("Duyệt không thành công! Không có thay đổi gì trên dữ liệu này.", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Approve Window.
    '''</summary>
    Friend Shared ReadOnly Property formText() As String
        Get
            Return ResourceManager.GetString("formText", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Error when mapping account with Corebank!.
    '''</summary>
    Friend Shared ReadOnly Property GetBankAcctnoError() As String
        Get
            Return ResourceManager.GetString("GetBankAcctnoError", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Apprv Required.
    '''</summary>
    Friend Shared ReadOnly Property grid_APPROVE_RQD() As String
        Get
            Return ResourceManager.GetString("grid.APPROVE_RQD", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Changed Info.
    '''</summary>
    Friend Shared ReadOnly Property grid_COLUMN_NAME() As String
        Get
            Return ResourceManager.GetString("grid.COLUMN_NAME", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Old Value.
    '''</summary>
    Friend Shared ReadOnly Property grid_FROM_VALUE() As String
        Get
            Return ResourceManager.GetString("grid.FROM_VALUE", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Modified Date.
    '''</summary>
    Friend Shared ReadOnly Property grid_MAKER_DT() As String
        Get
            Return ResourceManager.GetString("grid.MAKER_DT", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Maker time.
    '''</summary>
    Friend Shared ReadOnly Property grid_MAKER_TIME() As String
        Get
            Return ResourceManager.GetString("grid.MAKER_TIME", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Modification No.
    '''</summary>
    Friend Shared ReadOnly Property grid_MOD_NUM() As String
        Get
            Return ResourceManager.GetString("grid.MOD_NUM", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Maker Id.
    '''</summary>
    Friend Shared ReadOnly Property grid_TLNAME() As String
        Get
            Return ResourceManager.GetString("grid.TLNAME", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to New Value.
    '''</summary>
    Friend Shared ReadOnly Property grid_TO_VALUE() As String
        Get
            Return ResourceManager.GetString("grid.TO_VALUE", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Approval Denied! No changes have been made..
    '''</summary>
    Friend Shared ReadOnly Property NothingToApprove() As String
        Get
            Return ResourceManager.GetString("NothingToApprove", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Data is successfully rejected.
    '''</summary>
    Friend Shared ReadOnly Property RejectSuccessful() As String
        Get
            Return ResourceManager.GetString("RejectSuccessful", resourceCulture)
        End Get
    End Property
End Class
