'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace HOAuthService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="CTellerProfile", [Namespace]:="http://schemas.datacontract.org/2004/07/HostCommonLibrary"),  _
     System.SerializableAttribute()>  _
    Partial Public Class CTellerProfile
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AccessAreaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BranchIdField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BranchNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BusDateField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CompanyCodeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CompanyNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DescriptionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IPAddressField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IntervalField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LoginTimeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MacAddressField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NextDateField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PasswordField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TellerFullNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TellerGroupField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TellerGroupCareByField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TellerIdField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TellerLevelField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TellerNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TellerPrinterNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TellerRightField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TellerTitleField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TimeSearchField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AccessArea() As String
            Get
                Return Me.AccessAreaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AccessAreaField, value) <> true) Then
                    Me.AccessAreaField = value
                    Me.RaisePropertyChanged("AccessArea")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property BranchId() As String
            Get
                Return Me.BranchIdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.BranchIdField, value) <> true) Then
                    Me.BranchIdField = value
                    Me.RaisePropertyChanged("BranchId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property BranchName() As String
            Get
                Return Me.BranchNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.BranchNameField, value) <> true) Then
                    Me.BranchNameField = value
                    Me.RaisePropertyChanged("BranchName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property BusDate() As String
            Get
                Return Me.BusDateField
            End Get
            Set
                If (Object.ReferenceEquals(Me.BusDateField, value) <> true) Then
                    Me.BusDateField = value
                    Me.RaisePropertyChanged("BusDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CompanyCode() As String
            Get
                Return Me.CompanyCodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CompanyCodeField, value) <> true) Then
                    Me.CompanyCodeField = value
                    Me.RaisePropertyChanged("CompanyCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CompanyName() As String
            Get
                Return Me.CompanyNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CompanyNameField, value) <> true) Then
                    Me.CompanyNameField = value
                    Me.RaisePropertyChanged("CompanyName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Description() As String
            Get
                Return Me.DescriptionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DescriptionField, value) <> true) Then
                    Me.DescriptionField = value
                    Me.RaisePropertyChanged("Description")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IPAddress() As String
            Get
                Return Me.IPAddressField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IPAddressField, value) <> true) Then
                    Me.IPAddressField = value
                    Me.RaisePropertyChanged("IPAddress")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Interval() As String
            Get
                Return Me.IntervalField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IntervalField, value) <> true) Then
                    Me.IntervalField = value
                    Me.RaisePropertyChanged("Interval")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property LoginTime() As String
            Get
                Return Me.LoginTimeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LoginTimeField, value) <> true) Then
                    Me.LoginTimeField = value
                    Me.RaisePropertyChanged("LoginTime")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property MacAddress() As String
            Get
                Return Me.MacAddressField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MacAddressField, value) <> true) Then
                    Me.MacAddressField = value
                    Me.RaisePropertyChanged("MacAddress")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NextDate() As String
            Get
                Return Me.NextDateField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NextDateField, value) <> true) Then
                    Me.NextDateField = value
                    Me.RaisePropertyChanged("NextDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Password() As String
            Get
                Return Me.PasswordField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PasswordField, value) <> true) Then
                    Me.PasswordField = value
                    Me.RaisePropertyChanged("Password")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TellerFullName() As String
            Get
                Return Me.TellerFullNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TellerFullNameField, value) <> true) Then
                    Me.TellerFullNameField = value
                    Me.RaisePropertyChanged("TellerFullName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TellerGroup() As String
            Get
                Return Me.TellerGroupField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TellerGroupField, value) <> true) Then
                    Me.TellerGroupField = value
                    Me.RaisePropertyChanged("TellerGroup")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TellerGroupCareBy() As String
            Get
                Return Me.TellerGroupCareByField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TellerGroupCareByField, value) <> true) Then
                    Me.TellerGroupCareByField = value
                    Me.RaisePropertyChanged("TellerGroupCareBy")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TellerId() As String
            Get
                Return Me.TellerIdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TellerIdField, value) <> true) Then
                    Me.TellerIdField = value
                    Me.RaisePropertyChanged("TellerId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TellerLevel() As String
            Get
                Return Me.TellerLevelField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TellerLevelField, value) <> true) Then
                    Me.TellerLevelField = value
                    Me.RaisePropertyChanged("TellerLevel")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TellerName() As String
            Get
                Return Me.TellerNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TellerNameField, value) <> true) Then
                    Me.TellerNameField = value
                    Me.RaisePropertyChanged("TellerName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TellerPrinterName() As String
            Get
                Return Me.TellerPrinterNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TellerPrinterNameField, value) <> true) Then
                    Me.TellerPrinterNameField = value
                    Me.RaisePropertyChanged("TellerPrinterName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TellerRight() As String
            Get
                Return Me.TellerRightField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TellerRightField, value) <> true) Then
                    Me.TellerRightField = value
                    Me.RaisePropertyChanged("TellerRight")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TellerTitle() As String
            Get
                Return Me.TellerTitleField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TellerTitleField, value) <> true) Then
                    Me.TellerTitleField = value
                    Me.RaisePropertyChanged("TellerTitle")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TimeSearch() As String
            Get
                Return Me.TimeSearchField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TimeSearchField, value) <> true) Then
                    Me.TimeSearchField = value
                    Me.RaisePropertyChanged("TimeSearch")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="HOAuthService.IHOAuthService")>  _
    Public Interface IHOAuthService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IHOAuthService/DoWork", ReplyAction:="http://tempuri.org/IHOAuthService/DoWorkResponse")>  _
        Function DoWork(ByVal request As HOAuthService.DoWorkRequest) As HOAuthService.DoWorkResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IHOAuthService/DoWork", ReplyAction:="http://tempuri.org/IHOAuthService/DoWorkResponse")>  _
        Function DoWorkAsync(ByVal request As HOAuthService.DoWorkRequest) As System.Threading.Tasks.Task(Of HOAuthService.DoWorkResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IHOAuthService/GetAuthorizationTicket", ReplyAction:="http://tempuri.org/IHOAuthService/GetAuthorizationTicketResponse")>  _
        Function GetAuthorizationTicket(ByVal request As HOAuthService.GetAuthorizationTicketRequest) As HOAuthService.GetAuthorizationTicketResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IHOAuthService/GetAuthorizationTicket", ReplyAction:="http://tempuri.org/IHOAuthService/GetAuthorizationTicketResponse")>  _
        Function GetAuthorizationTicketAsync(ByVal request As HOAuthService.GetAuthorizationTicketRequest) As System.Threading.Tasks.Task(Of HOAuthService.GetAuthorizationTicketResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IHOAuthService/GetTellerProfile", ReplyAction:="http://tempuri.org/IHOAuthService/GetTellerProfileResponse")>  _
        Function GetTellerProfile(ByVal request As HOAuthService.GetTellerProfileRequest) As HOAuthService.GetTellerProfileResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IHOAuthService/GetTellerProfile", ReplyAction:="http://tempuri.org/IHOAuthService/GetTellerProfileResponse")>  _
        Function GetTellerProfileAsync(ByVal request As HOAuthService.GetTellerProfileRequest) As System.Threading.Tasks.Task(Of HOAuthService.GetTellerProfileResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IHOAuthService/GetLeftMenu", ReplyAction:="http://tempuri.org/IHOAuthService/GetLeftMenuResponse")>  _
        Function GetLeftMenu(ByVal request As HOAuthService.GetLeftMenuRequest) As HOAuthService.GetLeftMenuResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IHOAuthService/GetLeftMenu", ReplyAction:="http://tempuri.org/IHOAuthService/GetLeftMenuResponse")>  _
        Function GetLeftMenuAsync(ByVal request As HOAuthService.GetLeftMenuRequest) As System.Threading.Tasks.Task(Of HOAuthService.GetLeftMenuResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IHOAuthService/GetLeftAdjustMenu", ReplyAction:="http://tempuri.org/IHOAuthService/GetLeftAdjustMenuResponse")>  _
        Function GetLeftAdjustMenu(ByVal request As HOAuthService.GetLeftAdjustMenuRequest) As HOAuthService.GetLeftAdjustMenuResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IHOAuthService/GetLeftAdjustMenu", ReplyAction:="http://tempuri.org/IHOAuthService/GetLeftAdjustMenuResponse")>  _
        Function GetLeftAdjustMenuAsync(ByVal request As HOAuthService.GetLeftAdjustMenuRequest) As System.Threading.Tasks.Task(Of HOAuthService.GetLeftAdjustMenuResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="DoWork", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class DoWorkRequest
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="DoWorkResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class DoWorkResponse
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="GetAuthorizationTicket", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class GetAuthorizationTicketRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public pv_strUserName As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=1)>  _
        Public pv_strPassword As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal pv_strUserName As String, ByVal pv_strPassword As String)
            MyBase.New
            Me.pv_strUserName = pv_strUserName
            Me.pv_strPassword = pv_strPassword
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="GetAuthorizationTicketResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class GetAuthorizationTicketResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public GetAuthorizationTicketResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetAuthorizationTicketResult As String)
            MyBase.New
            Me.GetAuthorizationTicketResult = GetAuthorizationTicketResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="GetTellerProfile", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class GetTellerProfileRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public ticket As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ticket As String)
            MyBase.New
            Me.ticket = ticket
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="GetTellerProfileResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class GetTellerProfileResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public GetTellerProfileResult As HOAuthService.CTellerProfile
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetTellerProfileResult As HOAuthService.CTellerProfile)
            MyBase.New
            Me.GetTellerProfileResult = GetTellerProfileResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="GetLeftMenu", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class GetLeftMenuRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public message As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal message As String)
            MyBase.New
            Me.message = message
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="GetLeftMenuResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class GetLeftMenuResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public GetLeftMenuResult() As Byte
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetLeftMenuResult() As Byte)
            MyBase.New
            Me.GetLeftMenuResult = GetLeftMenuResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="GetLeftAdjustMenu", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class GetLeftAdjustMenuRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public message As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal message As String)
            MyBase.New
            Me.message = message
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="GetLeftAdjustMenuResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class GetLeftAdjustMenuResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public GetLeftAdjustMenuResult() As Byte
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetLeftAdjustMenuResult() As Byte)
            MyBase.New
            Me.GetLeftAdjustMenuResult = GetLeftAdjustMenuResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IHOAuthServiceChannel
        Inherits HOAuthService.IHOAuthService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class HOAuthServiceClient
        Inherits System.ServiceModel.ClientBase(Of HOAuthService.IHOAuthService)
        Implements HOAuthService.IHOAuthService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function DoWork(ByVal request As HOAuthService.DoWorkRequest) As HOAuthService.DoWorkResponse Implements HOAuthService.IHOAuthService.DoWork
            Return MyBase.Channel.DoWork(request)
        End Function
        
        Public Function DoWorkAsync(ByVal request As HOAuthService.DoWorkRequest) As System.Threading.Tasks.Task(Of HOAuthService.DoWorkResponse) Implements HOAuthService.IHOAuthService.DoWorkAsync
            Return MyBase.Channel.DoWorkAsync(request)
        End Function
        
        Public Function GetAuthorizationTicket(ByVal request As HOAuthService.GetAuthorizationTicketRequest) As HOAuthService.GetAuthorizationTicketResponse Implements HOAuthService.IHOAuthService.GetAuthorizationTicket
            Return MyBase.Channel.GetAuthorizationTicket(request)
        End Function
        
        Public Function GetAuthorizationTicketAsync(ByVal request As HOAuthService.GetAuthorizationTicketRequest) As System.Threading.Tasks.Task(Of HOAuthService.GetAuthorizationTicketResponse) Implements HOAuthService.IHOAuthService.GetAuthorizationTicketAsync
            Return MyBase.Channel.GetAuthorizationTicketAsync(request)
        End Function
        
        Public Function GetTellerProfile(ByVal request As HOAuthService.GetTellerProfileRequest) As HOAuthService.GetTellerProfileResponse Implements HOAuthService.IHOAuthService.GetTellerProfile
            Return MyBase.Channel.GetTellerProfile(request)
        End Function
        
        Public Function GetTellerProfileAsync(ByVal request As HOAuthService.GetTellerProfileRequest) As System.Threading.Tasks.Task(Of HOAuthService.GetTellerProfileResponse) Implements HOAuthService.IHOAuthService.GetTellerProfileAsync
            Return MyBase.Channel.GetTellerProfileAsync(request)
        End Function
        
        Public Function GetLeftMenu(ByVal request As HOAuthService.GetLeftMenuRequest) As HOAuthService.GetLeftMenuResponse Implements HOAuthService.IHOAuthService.GetLeftMenu
            Return MyBase.Channel.GetLeftMenu(request)
        End Function
        
        Public Function GetLeftMenuAsync(ByVal request As HOAuthService.GetLeftMenuRequest) As System.Threading.Tasks.Task(Of HOAuthService.GetLeftMenuResponse) Implements HOAuthService.IHOAuthService.GetLeftMenuAsync
            Return MyBase.Channel.GetLeftMenuAsync(request)
        End Function
        
        Public Function GetLeftAdjustMenu(ByVal request As HOAuthService.GetLeftAdjustMenuRequest) As HOAuthService.GetLeftAdjustMenuResponse Implements HOAuthService.IHOAuthService.GetLeftAdjustMenu
            Return MyBase.Channel.GetLeftAdjustMenu(request)
        End Function
        
        Public Function GetLeftAdjustMenuAsync(ByVal request As HOAuthService.GetLeftAdjustMenuRequest) As System.Threading.Tasks.Task(Of HOAuthService.GetLeftAdjustMenuResponse) Implements HOAuthService.IHOAuthService.GetLeftAdjustMenuAsync
            Return MyBase.Channel.GetLeftAdjustMenuAsync(request)
        End Function
    End Class
End Namespace
